In [1]:
import pandas as pd

In [2]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url)

test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url)

In [3]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [7]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
train["Age"].median()

28.0

In [10]:
train["Age"] = train["Age"].fillna(train["Age"].median())

In [11]:
train["Sex"] = train["Sex"].map({"male": 0, "female": 1})

In [12]:
train["Embarked"] = train["Embarked"].map({"S": 0, "C": 1, "Q": 2})

In [13]:
mode_embarked = train["Embarked"].mode()[0]
mode_embarked

np.float64(0.0)

In [14]:
train["Embarked"].fillna(mode_embarked, inplace=True)

/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3740535318.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Embarked"].fillna(mode_embarked, inplace=True)

In [15]:
mode_sex = train["Sex"].mode()[0]
mode_sex

np.int64(0)

In [16]:
train["Sex"].fillna(mode_sex, inplace=True)

/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/4126492801.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["Sex"].fillna(mode_sex, inplace=True)

In [17]:
test["Age"] = test["Age"].fillna(train["Age"].median())

In [18]:
test["Fare"] = test["Fare"].fillna(train["Fare"].median())

In [19]:
test["Sex"] = test["Sex"].map({"male": 0, "female": 1})

In [20]:
test["Embarked"] = test["Embarked"].map({"S": 0, "C": 1, "Q": 2})

In [21]:
import numpy as np

In [22]:
X = np.array(
    train[["Pclass", "Sex", "Age", "Embarked"]].values,
    dtype=float
)

y = np.array(train["Survived"].values, dtype=float)

In [23]:
X.shape, y.shape

((891, 4), (891,))

In [24]:
m = X.shape[0]
X = np.c_[np.ones(m), X]

In [63]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def predict_prob(X, w):
    return sigmoid(X @ w)
def compute_loss(X, y, w):
    m = len(y)
    y_hat = predict_prob(X, w)
    epsilon = 1e-8  # numerical stability
    return -(1/m) * np.sum(
        y * np.log(y_hat + epsilon) +
        (1 - y) * np.log(1 - y_hat + epsilon)
    )
def compute_gradient(X, y, w):
    m = len(y)
    y_hat = predict_prob(X, w)
    return (1/m) * (X.T @ (y_hat - y))
def gradient_descent(X, y, lr=0.1, decay=1e-3, epochs=5000):
    w = np.zeros(X.shape[1])
    losses = []

    for i in range(epochs):
        lr_t = lr / (1 + decay * i)  

        grad = compute_gradient(X, y, w)
        w -= lr_t * grad

        if i % 500 == 0:
            loss = compute_loss(X, y, w)
            losses.append(loss)
            print(f"Epoch {i}: lr={lr_t:.5f}, loss={loss:.4f}")

    return w, losses

In [75]:
w, losses = gradient_descent(X, y, epochs=1000000)

Epoch 0: lr=0.10000, loss=4.0893
Epoch 500: lr=0.06667, loss=6.2009
Epoch 1000: lr=0.05000, loss=0.6629
Epoch 1500: lr=0.04000, loss=1.3213
Epoch 2000: lr=0.03333, loss=0.6499
Epoch 2500: lr=0.02857, loss=0.6221
Epoch 3000: lr=0.02500, loss=0.5669
Epoch 3500: lr=0.02222, loss=0.5226
Epoch 4000: lr=0.02000, loss=0.4969
Epoch 4500: lr=0.01818, loss=0.4818
Epoch 5000: lr=0.01667, loss=0.4716
Epoch 5500: lr=0.01538, loss=0.4648
Epoch 6000: lr=0.01429, loss=0.4602
Epoch 6500: lr=0.01333, loss=0.4571
Epoch 7000: lr=0.01250, loss=0.4549
Epoch 7500: lr=0.01176, loss=0.4535
Epoch 8000: lr=0.01111, loss=0.4524
Epoch 8500: lr=0.01053, loss=0.4517
Epoch 9000: lr=0.01000, loss=0.4511
Epoch 9500: lr=0.00952, loss=0.4507
Epoch 10000: lr=0.00909, loss=0.4504
Epoch 10500: lr=0.00870, loss=0.4502
Epoch 11000: lr=0.00833, loss=0.4500
Epoch 11500: lr=0.00800, loss=0.4499
Epoch 12000: lr=0.00769, loss=0.4498
Epoch 12500: lr=0.00741, loss=0.4497
Epoch 13000: lr=0.00714, loss=0.4496
Epoch 13500: lr=0.00690, loss=0.4495
Epoch 14000: lr=0.00667, loss=0.4495
Epoch 14500: lr=0.00645, loss=0.4494
Epoch 15000: lr=0.00625, loss=0.4494
Epoch 15500: lr=0.00606, loss=0.4494
Epoch 16000: lr=0.00588, loss=0.4494
Epoch 16500: lr=0.00571, loss=0.4493
Epoch 17000: lr=0.00556, loss=0.4493
Epoch 17500: lr=0.00541, loss=0.4493
Epoch 18000: lr=0.00526, loss=0.4493
Epoch 18500: lr=0.00513, loss=0.4493
Epoch 19000: lr=0.00500, loss=0.4493
Epoch 19500: lr=0.00488, loss=0.4492
Epoch 20000: lr=0.00476, loss=0.4492
Epoch 20500: lr=0.00465, loss=0.4492
Epoch 21000: lr=0.00455, loss=0.4492
Epoch 21500: lr=0.00444, loss=0.4492
Epoch 22000: lr=0.00435, loss=0.4492
Epoch 22500: lr=0.00426, loss=0.4492
Epoch 23000: lr=0.00417, loss=0.4492
Epoch 23500: lr=0.00408, loss=0.4492
Epoch 24000: lr=0.00400, loss=0.4492
Epoch 24500: lr=0.00392, loss=0.4492
Epoch 25000: lr=0.00385, loss=0.4492
Epoch 25500: lr=0.00377, loss=0.4491
Epoch 26000: lr=0.00370, loss=0.4491
Epoch 26500: lr=0.00364, loss=0.4491
Epoch 27000: lr=0.00357, loss=0.4491
Epoch 27500: lr=0.00351, loss=0.4491
Epoch 28000: lr=0.00345, loss=0.4491
Epoch 28500: lr=0.00339, loss=0.4491
Epoch 29000: lr=0.00333, loss=0.4491
Epoch 29500: lr=0.00328, loss=0.4491
Epoch 30000: lr=0.00323, loss=0.4491
Epoch 30500: lr=0.00317, loss=0.4491
Epoch 31000: lr=0.00313, loss=0.4491
Epoch 31500: lr=0.00308, loss=0.4491
Epoch 32000: lr=0.00303, loss=0.4491
Epoch 32500: lr=0.00299, loss=0.4491
Epoch 33000: lr=0.00294, loss=0.4491
Epoch 33500: lr=0.00290, loss=0.4491
Epoch 34000: lr=0.00286, loss=0.4491
Epoch 34500: lr=0.00282, loss=0.4491
Epoch 35000: lr=0.00278, loss=0.4491
Epoch 35500: lr=0.00274, loss=0.4491
Epoch 36000: lr=0.00270, loss=0.4491
Epoch 36500: lr=0.00267, loss=0.4491
Epoch 37000: lr=0.00263, loss=0.4491
Epoch 37500: lr=0.00260, loss=0.4491
Epoch 38000: lr=0.00256, loss=0.4491
Epoch 38500: lr=0.00253, loss=0.4491
Epoch 39000: lr=0.00250, loss=0.4491
Epoch 39500: lr=0.00247, loss=0.4491
Epoch 40000: lr=0.00244, loss=0.4491
Epoch 40500: lr=0.00241, loss=0.4491
Epoch 41000: lr=0.00238, loss=0.4491
Epoch 41500: lr=0.00235, loss=0.4491
Epoch 42000: lr=0.00233, loss=0.4491
Epoch 42500: lr=0.00230, loss=0.4491
Epoch 43000: lr=0.00227, loss=0.4491
Epoch 43500: lr=0.00225, loss=0.4491
Epoch 44000: lr=0.00222, loss=0.4490
Epoch 44500: lr=0.00220, loss=0.4490
Epoch 45000: lr=0.00217, loss=0.4490
Epoch 45500: lr=0.00215, loss=0.4490
Epoch 46000: lr=0.00213, loss=0.4490
Epoch 46500: lr=0.00211, loss=0.4490
Epoch 47000: lr=0.00208, loss=0.4490
Epoch 47500: lr=0.00206, loss=0.4490
Epoch 48000: lr=0.00204, loss=0.4490
Epoch 48500: lr=0.00202, loss=0.4490
Epoch 49000: lr=0.00200, loss=0.4490
Epoch 49500: lr=0.00198, loss=0.4490
Epoch 50000: lr=0.00196, loss=0.4490
Epoch 50500: lr=0.00194, loss=0.4490
Epoch 51000: lr=0.00192, loss=0.4490
Epoch 51500: lr=0.00190, loss=0.4490
Epoch 52000: lr=0.00189, loss=0.4490
Epoch 52500: lr=0.00187, loss=0.4490
Epoch 53000: lr=0.00185, loss=0.4490
Epoch 53500: lr=0.00183, loss=0.4490
Epoch 54000: lr=0.00182, loss=0.4490
Epoch 54500: lr=0.00180, loss=0.4490
Epoch 55000: lr=0.00179, loss=0.4490
Epoch 55500: lr=0.00177, loss=0.4490
Epoch 56000: lr=0.00175, loss=0.4490
Epoch 56500: lr=0.00174, loss=0.4490
Epoch 57000: lr=0.00172, loss=0.4490
Epoch 57500: lr=0.00171, loss=0.4490
Epoch 58000: lr=0.00169, loss=0.4490
Epoch 58500: lr=0.00168, loss=0.4490
Epoch 59000: lr=0.00167, loss=0.4490
Epoch 59500: lr=0.00165, loss=0.4490
Epoch 60000: lr=0.00164, loss=0.4490
Epoch 60500: lr=0.00163, loss=0.4490
Epoch 61000: lr=0.00161, loss=0.4490
Epoch 61500: lr=0.00160, loss=0.4490
Epoch 62000: lr=0.00159, loss=0.4490
Epoch 62500: lr=0.00157, loss=0.4490
Epoch 63000: lr=0.00156, loss=0.4490
Epoch 63500: lr=0.00155, loss=0.4490
Epoch 64000: lr=0.00154, loss=0.4490
Epoch 64500: lr=0.00153, loss=0.4490
Epoch 65000: lr=0.00152, loss=0.4490
Epoch 65500: lr=0.00150, loss=0.4490
Epoch 66000: lr=0.00149, loss=0.4490
Epoch 66500: lr=0.00148, loss=0.4490
Epoch 67000: lr=0.00147, loss=0.4490
Epoch 67500: lr=0.00146, loss=0.4490
Epoch 68000: lr=0.00145, loss=0.4490
Epoch 68500: lr=0.00144, loss=0.4490
Epoch 69000: lr=0.00143, loss=0.4490
Epoch 69500: lr=0.00142, loss=0.4490
Epoch 70000: lr=0.00141, loss=0.4490
Epoch 70500: lr=0.00140, loss=0.4490
Epoch 71000: lr=0.00139, loss=0.4490
Epoch 71500: lr=0.00138, loss=0.4490
Epoch 72000: lr=0.00137, loss=0.4490
Epoch 72500: lr=0.00136, loss=0.4490
Epoch 73000: lr=0.00135, loss=0.4490
Epoch 73500: lr=0.00134, loss=0.4490
Epoch 74000: lr=0.00133, loss=0.4490
Epoch 74500: lr=0.00132, loss=0.4490
Epoch 75000: lr=0.00132, loss=0.4490
Epoch 75500: lr=0.00131, loss=0.4490
Epoch 76000: lr=0.00130, loss=0.4490
Epoch 76500: lr=0.00129, loss=0.4490
Epoch 77000: lr=0.00128, loss=0.4490
Epoch 77500: lr=0.00127, loss=0.4490
Epoch 78000: lr=0.00127, loss=0.4490
Epoch 78500: lr=0.00126, loss=0.4490
Epoch 79000: lr=0.00125, loss=0.4490
Epoch 79500: lr=0.00124, loss=0.4490
Epoch 80000: lr=0.00123, loss=0.4490
Epoch 80500: lr=0.00123, loss=0.4490
Epoch 81000: lr=0.00122, loss=0.4490
Epoch 81500: lr=0.00121, loss=0.4490
Epoch 82000: lr=0.00120, loss=0.4490
Epoch 82500: lr=0.00120, loss=0.4490
Epoch 83000: lr=0.00119, loss=0.4490
Epoch 83500: lr=0.00118, loss=0.4490
Epoch 84000: lr=0.00118, loss=0.4490
Epoch 84500: lr=0.00117, loss=0.4490
Epoch 85000: lr=0.00116, loss=0.4490
Epoch 85500: lr=0.00116, loss=0.4490
Epoch 86000: lr=0.00115, loss=0.4490
Epoch 86500: lr=0.00114, loss=0.4490
Epoch 87000: lr=0.00114, loss=0.4490
Epoch 87500: lr=0.00113, loss=0.4490
Epoch 88000: lr=0.00112, loss=0.4490
Epoch 88500: lr=0.00112, loss=0.4490
Epoch 89000: lr=0.00111, loss=0.4490
Epoch 89500: lr=0.00110, loss=0.4490
Epoch 90000: lr=0.00110, loss=0.4490
Epoch 90500: lr=0.00109, loss=0.4490
Epoch 91000: lr=0.00109, loss=0.4490
Epoch 91500: lr=0.00108, loss=0.4490
Epoch 92000: lr=0.00108, loss=0.4490
Epoch 92500: lr=0.00107, loss=0.4490
Epoch 93000: lr=0.00106, loss=0.4490
Epoch 93500: lr=0.00106, loss=0.4490
Epoch 94000: lr=0.00105, loss=0.4490
Epoch 94500: lr=0.00105, loss=0.4490
Epoch 95000: lr=0.00104, loss=0.4490
Epoch 95500: lr=0.00104, loss=0.4490
Epoch 96000: lr=0.00103, loss=0.4490
Epoch 96500: lr=0.00103, loss=0.4490
Epoch 97000: lr=0.00102, loss=0.4490
Epoch 97500: lr=0.00102, loss=0.4490
Epoch 98000: lr=0.00101, loss=0.4490
Epoch 98500: lr=0.00101, loss=0.4490
Epoch 99000: lr=0.00100, loss=0.4490
Epoch 99500: lr=0.00100, loss=0.4490
Epoch 100000: lr=0.00099, loss=0.4490
Epoch 100500: lr=0.00099, loss=0.4490
Epoch 101000: lr=0.00098, loss=0.4490
Epoch 101500: lr=0.00098, loss=0.4490
Epoch 102000: lr=0.00097, loss=0.4490
Epoch 102500: lr=0.00097, loss=0.4490
Epoch 103000: lr=0.00096, loss=0.4490
Epoch 103500: lr=0.00096, loss=0.4490
Epoch 104000: lr=0.00095, loss=0.4490
Epoch 104500: lr=0.00095, loss=0.4490
Epoch 105000: lr=0.00094, loss=0.4490
Epoch 105500: lr=0.00094, loss=0.4490
Epoch 106000: lr=0.00093, loss=0.4490
Epoch 106500: lr=0.00093, loss=0.4490
Epoch 107000: lr=0.00093, loss=0.4490
Epoch 107500: lr=0.00092, loss=0.4490
Epoch 108000: lr=0.00092, loss=0.4490
Epoch 108500: lr=0.00091, loss=0.4490
Epoch 109000: lr=0.00091, loss=0.4490
Epoch 109500: lr=0.00090, loss=0.4490
Epoch 110000: lr=0.00090, loss=0.4490
Epoch 110500: lr=0.00090, loss=0.4490
Epoch 111000: lr=0.00089, loss=0.4490
Epoch 111500: lr=0.00089, loss=0.4490
Epoch 112000: lr=0.00088, loss=0.4490
Epoch 112500: lr=0.00088, loss=0.4490
Epoch 113000: lr=0.00088, loss=0.4490
Epoch 113500: lr=0.00087, loss=0.4490
Epoch 114000: lr=0.00087, loss=0.4490
Epoch 114500: lr=0.00087, loss=0.4490
Epoch 115000: lr=0.00086, loss=0.4490
Epoch 115500: lr=0.00086, loss=0.4490
Epoch 116000: lr=0.00085, loss=0.4490
Epoch 116500: lr=0.00085, loss=0.4490
Epoch 117000: lr=0.00085, loss=0.4490
Epoch 117500: lr=0.00084, loss=0.4490
Epoch 118000: lr=0.00084, loss=0.4490
Epoch 118500: lr=0.00084, loss=0.4490
Epoch 119000: lr=0.00083, loss=0.4490
Epoch 119500: lr=0.00083, loss=0.4490
Epoch 120000: lr=0.00083, loss=0.4490
Epoch 120500: lr=0.00082, loss=0.4490
Epoch 121000: lr=0.00082, loss=0.4490
Epoch 121500: lr=0.00082, loss=0.4490
Epoch 122000: lr=0.00081, loss=0.4490
Epoch 122500: lr=0.00081, loss=0.4490
Epoch 123000: lr=0.00081, loss=0.4490
Epoch 123500: lr=0.00080, loss=0.4490
Epoch 124000: lr=0.00080, loss=0.4490

Epoch 124500: lr=0.00080, loss=0.4490
Epoch 125000: lr=0.00079, loss=0.4490
Epoch 125500: lr=0.00079, loss=0.4490
Epoch 126000: lr=0.00079, loss=0.4490
Epoch 126500: lr=0.00078, loss=0.4490
Epoch 127000: lr=0.00078, loss=0.4490
Epoch 127500: lr=0.00078, loss=0.4490
Epoch 128000: lr=0.00078, loss=0.4490
Epoch 128500: lr=0.00077, loss=0.4490
Epoch 129000: lr=0.00077, loss=0.4490
Epoch 129500: lr=0.00077, loss=0.4490
Epoch 130000: lr=0.00076, loss=0.4490
Epoch 130500: lr=0.00076, loss=0.4490
Epoch 131000: lr=0.00076, loss=0.4490
Epoch 131500: lr=0.00075, loss=0.4490
Epoch 132000: lr=0.00075, loss=0.4490
Epoch 132500: lr=0.00075, loss=0.4490
Epoch 133000: lr=0.00075, loss=0.4490
Epoch 133500: lr=0.00074, loss=0.4490
Epoch 134000: lr=0.00074, loss=0.4490
Epoch 134500: lr=0.00074, loss=0.4490
Epoch 135000: lr=0.00074, loss=0.4490
Epoch 135500: lr=0.00073, loss=0.4490
Epoch 136000: lr=0.00073, loss=0.4490
Epoch 136500: lr=0.00073, loss=0.4490
Epoch 137000: lr=0.00072, loss=0.4490
Epoch 137500: lr=0.00072, loss=0.4490
Epoch 138000: lr=0.00072, loss=0.4490
Epoch 138500: lr=0.00072, loss=0.4490
Epoch 139000: lr=0.00071, loss=0.4490
Epoch 139500: lr=0.00071, loss=0.4490
Epoch 140000: lr=0.00071, loss=0.4490
Epoch 140500: lr=0.00071, loss=0.4490
Epoch 141000: lr=0.00070, loss=0.4490
Epoch 141500: lr=0.00070, loss=0.4490
Epoch 142000: lr=0.00070, loss=0.4490
Epoch 142500: lr=0.00070, loss=0.4490
Epoch 143000: lr=0.00069, loss=0.4490
Epoch 143500: lr=0.00069, loss=0.4490
Epoch 144000: lr=0.00069, loss=0.4490
Epoch 144500: lr=0.00069, loss=0.4490
Epoch 145000: lr=0.00068, loss=0.4490
Epoch 145500: lr=0.00068, loss=0.4490
Epoch 146000: lr=0.00068, loss=0.4490
Epoch 146500: lr=0.00068, loss=0.4490
Epoch 147000: lr=0.00068, loss=0.4490
Epoch 147500: lr=0.00067, loss=0.4490
Epoch 148000: lr=0.00067, loss=0.4490
Epoch 148500: lr=0.00067, loss=0.4490
Epoch 149000: lr=0.00067, loss=0.4490
Epoch 149500: lr=0.00066, loss=0.4490
Epoch 150000: lr=0.00066, loss=0.4490
Epoch 150500: lr=0.00066, loss=0.4490
Epoch 151000: lr=0.00066, loss=0.4490
Epoch 151500: lr=0.00066, loss=0.4490
Epoch 152000: lr=0.00065, loss=0.4490
Epoch 152500: lr=0.00065, loss=0.4490
Epoch 153000: lr=0.00065, loss=0.4490
Epoch 153500: lr=0.00065, loss=0.4490
Epoch 154000: lr=0.00065, loss=0.4490
Epoch 154500: lr=0.00064, loss=0.4490
Epoch 155000: lr=0.00064, loss=0.4490
Epoch 155500: lr=0.00064, loss=0.4490
Epoch 156000: lr=0.00064, loss=0.4490
Epoch 156500: lr=0.00063, loss=0.4490
Epoch 157000: lr=0.00063, loss=0.4490
Epoch 157500: lr=0.00063, loss=0.4490
Epoch 158000: lr=0.00063, loss=0.4490
Epoch 158500: lr=0.00063, loss=0.4490
Epoch 159000: lr=0.00063, loss=0.4490
Epoch 159500: lr=0.00062, loss=0.4490
Epoch 160000: lr=0.00062, loss=0.4490
Epoch 160500: lr=0.00062, loss=0.4490
Epoch 161000: lr=0.00062, loss=0.4490
Epoch 161500: lr=0.00062, loss=0.4490
Epoch 162000: lr=0.00061, loss=0.4490
Epoch 162500: lr=0.00061, loss=0.4490
Epoch 163000: lr=0.00061, loss=0.4490
Epoch 163500: lr=0.00061, loss=0.4490
Epoch 164000: lr=0.00061, loss=0.4490
Epoch 164500: lr=0.00060, loss=0.4490
Epoch 165000: lr=0.00060, loss=0.4490
Epoch 165500: lr=0.00060, loss=0.4490
Epoch 166000: lr=0.00060, loss=0.4490
Epoch 166500: lr=0.00060, loss=0.4490
Epoch 167000: lr=0.00060, loss=0.4490
Epoch 167500: lr=0.00059, loss=0.4490
Epoch 168000: lr=0.00059, loss=0.4490
Epoch 168500: lr=0.00059, loss=0.4490
Epoch 169000: lr=0.00059, loss=0.4490
Epoch 169500: lr=0.00059, loss=0.4490
Epoch 170000: lr=0.00058, loss=0.4490
Epoch 170500: lr=0.00058, loss=0.4490
Epoch 171000: lr=0.00058, loss=0.4490
Epoch 171500: lr=0.00058, loss=0.4490
Epoch 172000: lr=0.00058, loss=0.4490
Epoch 172500: lr=0.00058, loss=0.4490
Epoch 173000: lr=0.00057, loss=0.4490
Epoch 173500: lr=0.00057, loss=0.4490
Epoch 174000: lr=0.00057, loss=0.4490
Epoch 174500: lr=0.00057, loss=0.4490
Epoch 175000: lr=0.00057, loss=0.4490
Epoch 175500: lr=0.00057, loss=0.4490
Epoch 176000: lr=0.00056, loss=0.4490
Epoch 176500: lr=0.00056, loss=0.4490
Epoch 177000: lr=0.00056, loss=0.4490
Epoch 177500: lr=0.00056, loss=0.4490
Epoch 178000: lr=0.00056, loss=0.4490
Epoch 178500: lr=0.00056, loss=0.4490
Epoch 179000: lr=0.00056, loss=0.4490
Epoch 179500: lr=0.00055, loss=0.4490
Epoch 180000: lr=0.00055, loss=0.4490
Epoch 180500: lr=0.00055, loss=0.4490
Epoch 181000: lr=0.00055, loss=0.4490
Epoch 181500: lr=0.00055, loss=0.4490
Epoch 182000: lr=0.00055, loss=0.4490
Epoch 182500: lr=0.00054, loss=0.4490
Epoch 183000: lr=0.00054, loss=0.4490
Epoch 183500: lr=0.00054, loss=0.4490
Epoch 184000: lr=0.00054, loss=0.4490
Epoch 184500: lr=0.00054, loss=0.4490
Epoch 185000: lr=0.00054, loss=0.4490
Epoch 185500: lr=0.00054, loss=0.4490
Epoch 186000: lr=0.00053, loss=0.4490
Epoch 186500: lr=0.00053, loss=0.4490
Epoch 187000: lr=0.00053, loss=0.4490
Epoch 187500: lr=0.00053, loss=0.4490
Epoch 188000: lr=0.00053, loss=0.4490
Epoch 188500: lr=0.00053, loss=0.4490
Epoch 189000: lr=0.00053, loss=0.4490
Epoch 189500: lr=0.00052, loss=0.4490
Epoch 190000: lr=0.00052, loss=0.4490
Epoch 190500: lr=0.00052, loss=0.4490
Epoch 191000: lr=0.00052, loss=0.4490
Epoch 191500: lr=0.00052, loss=0.4490
Epoch 192000: lr=0.00052, loss=0.4490
Epoch 192500: lr=0.00052, loss=0.4490
Epoch 193000: lr=0.00052, loss=0.4490
Epoch 193500: lr=0.00051, loss=0.4490
Epoch 194000: lr=0.00051, loss=0.4490
Epoch 194500: lr=0.00051, loss=0.4490
Epoch 195000: lr=0.00051, loss=0.4490
Epoch 195500: lr=0.00051, loss=0.4490
Epoch 196000: lr=0.00051, loss=0.4490
Epoch 196500: lr=0.00051, loss=0.4490
Epoch 197000: lr=0.00051, loss=0.4490
Epoch 197500: lr=0.00050, loss=0.4490
Epoch 198000: lr=0.00050, loss=0.4490
Epoch 198500: lr=0.00050, loss=0.4490
Epoch 199000: lr=0.00050, loss=0.4490
Epoch 199500: lr=0.00050, loss=0.4490
Epoch 200000: lr=0.00050, loss=0.4490
Epoch 200500: lr=0.00050, loss=0.4490
Epoch 201000: lr=0.00050, loss=0.4490
Epoch 201500: lr=0.00049, loss=0.4490
Epoch 202000: lr=0.00049, loss=0.4490
Epoch 202500: lr=0.00049, loss=0.4490
Epoch 203000: lr=0.00049, loss=0.4490
Epoch 203500: lr=0.00049, loss=0.4490
Epoch 204000: lr=0.00049, loss=0.4490
Epoch 204500: lr=0.00049, loss=0.4490
Epoch 205000: lr=0.00049, loss=0.4490
Epoch 205500: lr=0.00048, loss=0.4490
Epoch 206000: lr=0.00048, loss=0.4490
Epoch 206500: lr=0.00048, loss=0.4490
Epoch 207000: lr=0.00048, loss=0.4490
Epoch 207500: lr=0.00048, loss=0.4490
Epoch 208000: lr=0.00048, loss=0.4490
Epoch 208500: lr=0.00048, loss=0.4490
Epoch 209000: lr=0.00048, loss=0.4490
Epoch 209500: lr=0.00048, loss=0.4490
Epoch 210000: lr=0.00047, loss=0.4490
Epoch 210500: lr=0.00047, loss=0.4490
Epoch 211000: lr=0.00047, loss=0.4490
Epoch 211500: lr=0.00047, loss=0.4490
Epoch 212000: lr=0.00047, loss=0.4490
Epoch 212500: lr=0.00047, loss=0.4490
Epoch 213000: lr=0.00047, loss=0.4490
Epoch 213500: lr=0.00047, loss=0.4490
Epoch 214000: lr=0.00047, loss=0.4490
Epoch 214500: lr=0.00046, loss=0.4490
Epoch 215000: lr=0.00046, loss=0.4490
Epoch 215500: lr=0.00046, loss=0.4490
Epoch 216000: lr=0.00046, loss=0.4490
Epoch 216500: lr=0.00046, loss=0.4490
Epoch 217000: lr=0.00046, loss=0.4490
Epoch 217500: lr=0.00046, loss=0.4490
Epoch 218000: lr=0.00046, loss=0.4490
Epoch 218500: lr=0.00046, loss=0.4490
Epoch 219000: lr=0.00045, loss=0.4490
Epoch 219500: lr=0.00045, loss=0.4490
Epoch 220000: lr=0.00045, loss=0.4490
Epoch 220500: lr=0.00045, loss=0.4490
Epoch 221000: lr=0.00045, loss=0.4490
Epoch 221500: lr=0.00045, loss=0.4490
Epoch 222000: lr=0.00045, loss=0.4490
Epoch 222500: lr=0.00045, loss=0.4490
Epoch 223000: lr=0.00045, loss=0.4490
Epoch 223500: lr=0.00045, loss=0.4490
Epoch 224000: lr=0.00044, loss=0.4490
Epoch 224500: lr=0.00044, loss=0.4490
Epoch 225000: lr=0.00044, loss=0.4490
Epoch 225500: lr=0.00044, loss=0.4490
Epoch 226000: lr=0.00044, loss=0.4490
Epoch 226500: lr=0.00044, loss=0.4490
Epoch 227000: lr=0.00044, loss=0.4490
Epoch 227500: lr=0.00044, loss=0.4490
Epoch 228000: lr=0.00044, loss=0.4490
Epoch 228500: lr=0.00044, loss=0.4490
Epoch 229000: lr=0.00043, loss=0.4490
Epoch 229500: lr=0.00043, loss=0.4490
Epoch 230000: lr=0.00043, loss=0.4490
Epoch 230500: lr=0.00043, loss=0.4490
Epoch 231000: lr=0.00043, loss=0.4490
Epoch 231500: lr=0.00043, loss=0.4490
Epoch 232000: lr=0.00043, loss=0.4490
Epoch 232500: lr=0.00043, loss=0.4490
Epoch 233000: lr=0.00043, loss=0.4490
Epoch 233500: lr=0.00043, loss=0.4490
Epoch 234000: lr=0.00043, loss=0.4490

Epoch 234500: lr=0.00042, loss=0.4490
Epoch 235000: lr=0.00042, loss=0.4490
Epoch 235500: lr=0.00042, loss=0.4490
Epoch 236000: lr=0.00042, loss=0.4490
Epoch 236500: lr=0.00042, loss=0.4490
Epoch 237000: lr=0.00042, loss=0.4490
Epoch 237500: lr=0.00042, loss=0.4490
Epoch 238000: lr=0.00042, loss=0.4490
Epoch 238500: lr=0.00042, loss=0.4490
Epoch 239000: lr=0.00042, loss=0.4490
Epoch 239500: lr=0.00042, loss=0.4490
Epoch 240000: lr=0.00041, loss=0.4490
Epoch 240500: lr=0.00041, loss=0.4490
Epoch 241000: lr=0.00041, loss=0.4490
Epoch 241500: lr=0.00041, loss=0.4490
Epoch 242000: lr=0.00041, loss=0.4490
Epoch 242500: lr=0.00041, loss=0.4490
Epoch 243000: lr=0.00041, loss=0.4490
Epoch 243500: lr=0.00041, loss=0.4490
Epoch 244000: lr=0.00041, loss=0.4490
Epoch 244500: lr=0.00041, loss=0.4490
Epoch 245000: lr=0.00041, loss=0.4490
Epoch 245500: lr=0.00041, loss=0.4490
Epoch 246000: lr=0.00040, loss=0.4490
Epoch 246500: lr=0.00040, loss=0.4490
Epoch 247000: lr=0.00040, loss=0.4490
Epoch 247500: lr=0.00040, loss=0.4490
Epoch 248000: lr=0.00040, loss=0.4490
Epoch 248500: lr=0.00040, loss=0.4490
Epoch 249000: lr=0.00040, loss=0.4490
Epoch 249500: lr=0.00040, loss=0.4490
Epoch 250000: lr=0.00040, loss=0.4490
Epoch 250500: lr=0.00040, loss=0.4490
Epoch 251000: lr=0.00040, loss=0.4490
Epoch 251500: lr=0.00040, loss=0.4490
Epoch 252000: lr=0.00040, loss=0.4490
Epoch 252500: lr=0.00039, loss=0.4490
Epoch 253000: lr=0.00039, loss=0.4490
Epoch 253500: lr=0.00039, loss=0.4490
Epoch 254000: lr=0.00039, loss=0.4490
Epoch 254500: lr=0.00039, loss=0.4490
Epoch 255000: lr=0.00039, loss=0.4490
Epoch 255500: lr=0.00039, loss=0.4490
Epoch 256000: lr=0.00039, loss=0.4490
Epoch 256500: lr=0.00039, loss=0.4490
Epoch 257000: lr=0.00039, loss=0.4490
Epoch 257500: lr=0.00039, loss=0.4490
Epoch 258000: lr=0.00039, loss=0.4490
Epoch 258500: lr=0.00039, loss=0.4490
Epoch 259000: lr=0.00038, loss=0.4490
Epoch 259500: lr=0.00038, loss=0.4490
Epoch 260000: lr=0.00038, loss=0.4490
Epoch 260500: lr=0.00038, loss=0.4490
Epoch 261000: lr=0.00038, loss=0.4490
Epoch 261500: lr=0.00038, loss=0.4490
Epoch 262000: lr=0.00038, loss=0.4490
Epoch 262500: lr=0.00038, loss=0.4490
Epoch 263000: lr=0.00038, loss=0.4490
Epoch 263500: lr=0.00038, loss=0.4490
Epoch 264000: lr=0.00038, loss=0.4490
Epoch 264500: lr=0.00038, loss=0.4490
Epoch 265000: lr=0.00038, loss=0.4490
Epoch 265500: lr=0.00038, loss=0.4490
Epoch 266000: lr=0.00037, loss=0.4490
Epoch 266500: lr=0.00037, loss=0.4490
Epoch 267000: lr=0.00037, loss=0.4490
Epoch 267500: lr=0.00037, loss=0.4490
Epoch 268000: lr=0.00037, loss=0.4490
Epoch 268500: lr=0.00037, loss=0.4490
Epoch 269000: lr=0.00037, loss=0.4490
Epoch 269500: lr=0.00037, loss=0.4490
Epoch 270000: lr=0.00037, loss=0.4490
Epoch 270500: lr=0.00037, loss=0.4490
Epoch 271000: lr=0.00037, loss=0.4490
Epoch 271500: lr=0.00037, loss=0.4490
Epoch 272000: lr=0.00037, loss=0.4490
Epoch 272500: lr=0.00037, loss=0.4490
Epoch 273000: lr=0.00036, loss=0.4490
Epoch 273500: lr=0.00036, loss=0.4490
Epoch 274000: lr=0.00036, loss=0.4490
Epoch 274500: lr=0.00036, loss=0.4490
Epoch 275000: lr=0.00036, loss=0.4490
Epoch 275500: lr=0.00036, loss=0.4490
Epoch 276000: lr=0.00036, loss=0.4490
Epoch 276500: lr=0.00036, loss=0.4490
Epoch 277000: lr=0.00036, loss=0.4490
Epoch 277500: lr=0.00036, loss=0.4490
Epoch 278000: lr=0.00036, loss=0.4490
Epoch 278500: lr=0.00036, loss=0.4490
Epoch 279000: lr=0.00036, loss=0.4490
Epoch 279500: lr=0.00036, loss=0.4490
Epoch 280000: lr=0.00036, loss=0.4490
Epoch 280500: lr=0.00036, loss=0.4490
Epoch 281000: lr=0.00035, loss=0.4490
Epoch 281500: lr=0.00035, loss=0.4490
Epoch 282000: lr=0.00035, loss=0.4490
Epoch 282500: lr=0.00035, loss=0.4490
Epoch 283000: lr=0.00035, loss=0.4490
Epoch 283500: lr=0.00035, loss=0.4490
Epoch 284000: lr=0.00035, loss=0.4490
Epoch 284500: lr=0.00035, loss=0.4490
Epoch 285000: lr=0.00035, loss=0.4490
Epoch 285500: lr=0.00035, loss=0.4490
Epoch 286000: lr=0.00035, loss=0.4490
Epoch 286500: lr=0.00035, loss=0.4490
Epoch 287000: lr=0.00035, loss=0.4490
Epoch 287500: lr=0.00035, loss=0.4490
Epoch 288000: lr=0.00035, loss=0.4490
Epoch 288500: lr=0.00035, loss=0.4490
Epoch 289000: lr=0.00034, loss=0.4490
Epoch 289500: lr=0.00034, loss=0.4490
Epoch 290000: lr=0.00034, loss=0.4490
Epoch 290500: lr=0.00034, loss=0.4490
Epoch 291000: lr=0.00034, loss=0.4490
Epoch 291500: lr=0.00034, loss=0.4490
Epoch 292000: lr=0.00034, loss=0.4490
Epoch 292500: lr=0.00034, loss=0.4490
Epoch 293000: lr=0.00034, loss=0.4490
Epoch 293500: lr=0.00034, loss=0.4490
Epoch 294000: lr=0.00034, loss=0.4490
Epoch 294500: lr=0.00034, loss=0.4490
Epoch 295000: lr=0.00034, loss=0.4490
Epoch 295500: lr=0.00034, loss=0.4490
Epoch 296000: lr=0.00034, loss=0.4490
Epoch 296500: lr=0.00034, loss=0.4490
Epoch 297000: lr=0.00034, loss=0.4490
Epoch 297500: lr=0.00034, loss=0.4490
Epoch 298000: lr=0.00033, loss=0.4490
Epoch 298500: lr=0.00033, loss=0.4490
Epoch 299000: lr=0.00033, loss=0.4490
Epoch 299500: lr=0.00033, loss=0.4490
Epoch 300000: lr=0.00033, loss=0.4490
Epoch 300500: lr=0.00033, loss=0.4490
Epoch 301000: lr=0.00033, loss=0.4490
Epoch 301500: lr=0.00033, loss=0.4490
Epoch 302000: lr=0.00033, loss=0.4490
Epoch 302500: lr=0.00033, loss=0.4490
Epoch 303000: lr=0.00033, loss=0.4490
Epoch 303500: lr=0.00033, loss=0.4490
Epoch 304000: lr=0.00033, loss=0.4490
Epoch 304500: lr=0.00033, loss=0.4490
Epoch 305000: lr=0.00033, loss=0.4490
Epoch 305500: lr=0.00033, loss=0.4490
Epoch 306000: lr=0.00033, loss=0.4490
Epoch 306500: lr=0.00033, loss=0.4490
Epoch 307000: lr=0.00032, loss=0.4490
Epoch 307500: lr=0.00032, loss=0.4490
Epoch 308000: lr=0.00032, loss=0.4490
Epoch 308500: lr=0.00032, loss=0.4490
Epoch 309000: lr=0.00032, loss=0.4490
Epoch 309500: lr=0.00032, loss=0.4490
Epoch 310000: lr=0.00032, loss=0.4490
Epoch 310500: lr=0.00032, loss=0.4490
Epoch 311000: lr=0.00032, loss=0.4490
Epoch 311500: lr=0.00032, loss=0.4490
Epoch 312000: lr=0.00032, loss=0.4490
Epoch 312500: lr=0.00032, loss=0.4490
Epoch 313000: lr=0.00032, loss=0.4490
Epoch 313500: lr=0.00032, loss=0.4490
Epoch 314000: lr=0.00032, loss=0.4490
Epoch 314500: lr=0.00032, loss=0.4490
Epoch 315000: lr=0.00032, loss=0.4490
Epoch 315500: lr=0.00032, loss=0.4490
Epoch 316000: lr=0.00032, loss=0.4490
Epoch 316500: lr=0.00031, loss=0.4490
Epoch 317000: lr=0.00031, loss=0.4490
Epoch 317500: lr=0.00031, loss=0.4490
Epoch 318000: lr=0.00031, loss=0.4490
Epoch 318500: lr=0.00031, loss=0.4490
Epoch 319000: lr=0.00031, loss=0.4490
Epoch 319500: lr=0.00031, loss=0.4490
Epoch 320000: lr=0.00031, loss=0.4490
Epoch 320500: lr=0.00031, loss=0.4490
Epoch 321000: lr=0.00031, loss=0.4490
Epoch 321500: lr=0.00031, loss=0.4490
Epoch 322000: lr=0.00031, loss=0.4490
Epoch 322500: lr=0.00031, loss=0.4490
Epoch 323000: lr=0.00031, loss=0.4490
Epoch 323500: lr=0.00031, loss=0.4490
Epoch 324000: lr=0.00031, loss=0.4490
Epoch 324500: lr=0.00031, loss=0.4490
Epoch 325000: lr=0.00031, loss=0.4490
Epoch 325500: lr=0.00031, loss=0.4490
Epoch 326000: lr=0.00031, loss=0.4490
Epoch 326500: lr=0.00031, loss=0.4490
Epoch 327000: lr=0.00030, loss=0.4490
Epoch 327500: lr=0.00030, loss=0.4490
Epoch 328000: lr=0.00030, loss=0.4490
Epoch 328500: lr=0.00030, loss=0.4490
Epoch 329000: lr=0.00030, loss=0.4490
Epoch 329500: lr=0.00030, loss=0.4490
Epoch 330000: lr=0.00030, loss=0.4490
Epoch 330500: lr=0.00030, loss=0.4490
Epoch 331000: lr=0.00030, loss=0.4490
Epoch 331500: lr=0.00030, loss=0.4490
Epoch 332000: lr=0.00030, loss=0.4490
Epoch 332500: lr=0.00030, loss=0.4490
Epoch 333000: lr=0.00030, loss=0.4490
Epoch 333500: lr=0.00030, loss=0.4490
Epoch 334000: lr=0.00030, loss=0.4490
Epoch 334500: lr=0.00030, loss=0.4490
Epoch 335000: lr=0.00030, loss=0.4490
Epoch 335500: lr=0.00030, loss=0.4490
Epoch 336000: lr=0.00030, loss=0.4490
Epoch 336500: lr=0.00030, loss=0.4490
Epoch 337000: lr=0.00030, loss=0.4490
Epoch 337500: lr=0.00030, loss=0.4490
Epoch 338000: lr=0.00029, loss=0.4490
Epoch 338500: lr=0.00029, loss=0.4490
Epoch 339000: lr=0.00029, loss=0.4490
Epoch 339500: lr=0.00029, loss=0.4490
Epoch 340000: lr=0.00029, loss=0.4490
Epoch 340500: lr=0.00029, loss=0.4490
Epoch 341000: lr=0.00029, loss=0.4490
Epoch 341500: lr=0.00029, loss=0.4490
Epoch 342000: lr=0.00029, loss=0.4490
Epoch 342500: lr=0.00029, loss=0.4490
Epoch 343000: lr=0.00029, loss=0.4490
Epoch 343500: lr=0.00029, loss=0.4490
Epoch 344000: lr=0.00029, loss=0.4490
Epoch 344500: lr=0.00029, loss=0.4490
Epoch 345000: lr=0.00029, loss=0.4490
Epoch 345500: lr=0.00029, loss=0.4490
Epoch 346000: lr=0.00029, loss=0.4490
Epoch 346500: lr=0.00029, loss=0.4490

Epoch 347000: lr=0.00029, loss=0.4490
Epoch 347500: lr=0.00029, loss=0.4490
Epoch 348000: lr=0.00029, loss=0.4490
Epoch 348500: lr=0.00029, loss=0.4490
Epoch 349000: lr=0.00029, loss=0.4490
Epoch 349500: lr=0.00029, loss=0.4490
Epoch 350000: lr=0.00028, loss=0.4490
Epoch 350500: lr=0.00028, loss=0.4490
Epoch 351000: lr=0.00028, loss=0.4490
Epoch 351500: lr=0.00028, loss=0.4490
Epoch 352000: lr=0.00028, loss=0.4490
Epoch 352500: lr=0.00028, loss=0.4490
Epoch 353000: lr=0.00028, loss=0.4490
Epoch 353500: lr=0.00028, loss=0.4490
Epoch 354000: lr=0.00028, loss=0.4490
Epoch 354500: lr=0.00028, loss=0.4490
Epoch 355000: lr=0.00028, loss=0.4490
Epoch 355500: lr=0.00028, loss=0.4490
Epoch 356000: lr=0.00028, loss=0.4490
Epoch 356500: lr=0.00028, loss=0.4490
Epoch 357000: lr=0.00028, loss=0.4490
Epoch 357500: lr=0.00028, loss=0.4490
Epoch 358000: lr=0.00028, loss=0.4490
Epoch 358500: lr=0.00028, loss=0.4490
Epoch 359000: lr=0.00028, loss=0.4490
Epoch 359500: lr=0.00028, loss=0.4490
Epoch 360000: lr=0.00028, loss=0.4490
Epoch 360500: lr=0.00028, loss=0.4490
Epoch 361000: lr=0.00028, loss=0.4490
Epoch 361500: lr=0.00028, loss=0.4490
Epoch 362000: lr=0.00028, loss=0.4490
Epoch 362500: lr=0.00028, loss=0.4490
Epoch 363000: lr=0.00027, loss=0.4490
Epoch 363500: lr=0.00027, loss=0.4490
Epoch 364000: lr=0.00027, loss=0.4490
Epoch 364500: lr=0.00027, loss=0.4490
Epoch 365000: lr=0.00027, loss=0.4490
Epoch 365500: lr=0.00027, loss=0.4490
Epoch 366000: lr=0.00027, loss=0.4490
Epoch 366500: lr=0.00027, loss=0.4490
Epoch 367000: lr=0.00027, loss=0.4490
Epoch 367500: lr=0.00027, loss=0.4490
Epoch 368000: lr=0.00027, loss=0.4490
Epoch 368500: lr=0.00027, loss=0.4490
Epoch 369000: lr=0.00027, loss=0.4490
Epoch 369500: lr=0.00027, loss=0.4490
Epoch 370000: lr=0.00027, loss=0.4490
Epoch 370500: lr=0.00027, loss=0.4490
Epoch 371000: lr=0.00027, loss=0.4490
Epoch 371500: lr=0.00027, loss=0.4490
Epoch 372000: lr=0.00027, loss=0.4490
Epoch 372500: lr=0.00027, loss=0.4490
Epoch 373000: lr=0.00027, loss=0.4490
Epoch 373500: lr=0.00027, loss=0.4490
Epoch 374000: lr=0.00027, loss=0.4490
Epoch 374500: lr=0.00027, loss=0.4490
Epoch 375000: lr=0.00027, loss=0.4490
Epoch 375500: lr=0.00027, loss=0.4490
Epoch 376000: lr=0.00027, loss=0.4490
Epoch 376500: lr=0.00026, loss=0.4490
Epoch 377000: lr=0.00026, loss=0.4490
Epoch 377500: lr=0.00026, loss=0.4490
Epoch 378000: lr=0.00026, loss=0.4490
Epoch 378500: lr=0.00026, loss=0.4490
Epoch 379000: lr=0.00026, loss=0.4490
Epoch 379500: lr=0.00026, loss=0.4490
Epoch 380000: lr=0.00026, loss=0.4490
Epoch 380500: lr=0.00026, loss=0.4490
Epoch 381000: lr=0.00026, loss=0.4490
Epoch 381500: lr=0.00026, loss=0.4490
Epoch 382000: lr=0.00026, loss=0.4490
Epoch 382500: lr=0.00026, loss=0.4490
Epoch 383000: lr=0.00026, loss=0.4490
Epoch 383500: lr=0.00026, loss=0.4490
Epoch 384000: lr=0.00026, loss=0.4490
Epoch 384500: lr=0.00026, loss=0.4490
Epoch 385000: lr=0.00026, loss=0.4490
Epoch 385500: lr=0.00026, loss=0.4490
Epoch 386000: lr=0.00026, loss=0.4490
Epoch 386500: lr=0.00026, loss=0.4490
Epoch 387000: lr=0.00026, loss=0.4490
Epoch 387500: lr=0.00026, loss=0.4490
Epoch 388000: lr=0.00026, loss=0.4490
Epoch 388500: lr=0.00026, loss=0.4490
Epoch 389000: lr=0.00026, loss=0.4490
Epoch 389500: lr=0.00026, loss=0.4490
Epoch 390000: lr=0.00026, loss=0.4490
Epoch 390500: lr=0.00026, loss=0.4490
Epoch 391000: lr=0.00026, loss=0.4490
Epoch 391500: lr=0.00025, loss=0.4490
Epoch 392000: lr=0.00025, loss=0.4490
Epoch 392500: lr=0.00025, loss=0.4490
Epoch 393000: lr=0.00025, loss=0.4490
Epoch 393500: lr=0.00025, loss=0.4490
Epoch 394000: lr=0.00025, loss=0.4490
Epoch 394500: lr=0.00025, loss=0.4490
Epoch 395000: lr=0.00025, loss=0.4490
Epoch 395500: lr=0.00025, loss=0.4490
Epoch 396000: lr=0.00025, loss=0.4490
Epoch 396500: lr=0.00025, loss=0.4490
Epoch 397000: lr=0.00025, loss=0.4490
Epoch 397500: lr=0.00025, loss=0.4490
Epoch 398000: lr=0.00025, loss=0.4490
Epoch 398500: lr=0.00025, loss=0.4490
Epoch 399000: lr=0.00025, loss=0.4490
Epoch 399500: lr=0.00025, loss=0.4490
Epoch 400000: lr=0.00025, loss=0.4490
Epoch 400500: lr=0.00025, loss=0.4490
Epoch 401000: lr=0.00025, loss=0.4490
Epoch 401500: lr=0.00025, loss=0.4490
Epoch 402000: lr=0.00025, loss=0.4490
Epoch 402500: lr=0.00025, loss=0.4490
Epoch 403000: lr=0.00025, loss=0.4490
Epoch 403500: lr=0.00025, loss=0.4490
Epoch 404000: lr=0.00025, loss=0.4490
Epoch 404500: lr=0.00025, loss=0.4490
Epoch 405000: lr=0.00025, loss=0.4490
Epoch 405500: lr=0.00025, loss=0.4490
Epoch 406000: lr=0.00025, loss=0.4490
Epoch 406500: lr=0.00025, loss=0.4490
Epoch 407000: lr=0.00025, loss=0.4490
Epoch 407500: lr=0.00024, loss=0.4490
Epoch 408000: lr=0.00024, loss=0.4490
Epoch 408500: lr=0.00024, loss=0.4490
Epoch 409000: lr=0.00024, loss=0.4490
Epoch 409500: lr=0.00024, loss=0.4490
Epoch 410000: lr=0.00024, loss=0.4490
Epoch 410500: lr=0.00024, loss=0.4490
Epoch 411000: lr=0.00024, loss=0.4490
Epoch 411500: lr=0.00024, loss=0.4490
Epoch 412000: lr=0.00024, loss=0.4490
Epoch 412500: lr=0.00024, loss=0.4490
Epoch 413000: lr=0.00024, loss=0.4490
Epoch 413500: lr=0.00024, loss=0.4490
Epoch 414000: lr=0.00024, loss=0.4490
Epoch 414500: lr=0.00024, loss=0.4490
Epoch 415000: lr=0.00024, loss=0.4490
Epoch 415500: lr=0.00024, loss=0.4490
Epoch 416000: lr=0.00024, loss=0.4490
Epoch 416500: lr=0.00024, loss=0.4490
Epoch 417000: lr=0.00024, loss=0.4490
Epoch 417500: lr=0.00024, loss=0.4490
Epoch 418000: lr=0.00024, loss=0.4490
Epoch 418500: lr=0.00024, loss=0.4490
Epoch 419000: lr=0.00024, loss=0.4490
Epoch 419500: lr=0.00024, loss=0.4490
Epoch 420000: lr=0.00024, loss=0.4490
Epoch 420500: lr=0.00024, loss=0.4490
Epoch 421000: lr=0.00024, loss=0.4490
Epoch 421500: lr=0.00024, loss=0.4490
Epoch 422000: lr=0.00024, loss=0.4490
Epoch 422500: lr=0.00024, loss=0.4490
Epoch 423000: lr=0.00024, loss=0.4490
Epoch 423500: lr=0.00024, loss=0.4490
Epoch 424000: lr=0.00024, loss=0.4490
Epoch 424500: lr=0.00024, loss=0.4490
Epoch 425000: lr=0.00023, loss=0.4490
Epoch 425500: lr=0.00023, loss=0.4490
Epoch 426000: lr=0.00023, loss=0.4490
Epoch 426500: lr=0.00023, loss=0.4490
Epoch 427000: lr=0.00023, loss=0.4490
Epoch 427500: lr=0.00023, loss=0.4490
Epoch 428000: lr=0.00023, loss=0.4490
Epoch 428500: lr=0.00023, loss=0.4490
Epoch 429000: lr=0.00023, loss=0.4490
Epoch 429500: lr=0.00023, loss=0.4490
Epoch 430000: lr=0.00023, loss=0.4490
Epoch 430500: lr=0.00023, loss=0.4490
Epoch 431000: lr=0.00023, loss=0.4490
Epoch 431500: lr=0.00023, loss=0.4490
Epoch 432000: lr=0.00023, loss=0.4490
Epoch 432500: lr=0.00023, loss=0.4490
Epoch 433000: lr=0.00023, loss=0.4490
Epoch 433500: lr=0.00023, loss=0.4490
Epoch 434000: lr=0.00023, loss=0.4490
Epoch 434500: lr=0.00023, loss=0.4490
Epoch 435000: lr=0.00023, loss=0.4490
Epoch 435500: lr=0.00023, loss=0.4490
Epoch 436000: lr=0.00023, loss=0.4490
Epoch 436500: lr=0.00023, loss=0.4490
Epoch 437000: lr=0.00023, loss=0.4490
Epoch 437500: lr=0.00023, loss=0.4490
Epoch 438000: lr=0.00023, loss=0.4490
Epoch 438500: lr=0.00023, loss=0.4490
Epoch 439000: lr=0.00023, loss=0.4490
Epoch 439500: lr=0.00023, loss=0.4490
Epoch 440000: lr=0.00023, loss=0.4490
Epoch 440500: lr=0.00023, loss=0.4490
Epoch 441000: lr=0.00023, loss=0.4490
Epoch 441500: lr=0.00023, loss=0.4490
Epoch 442000: lr=0.00023, loss=0.4490
Epoch 442500: lr=0.00023, loss=0.4490
Epoch 443000: lr=0.00023, loss=0.4490
Epoch 443500: lr=0.00022, loss=0.4490
Epoch 444000: lr=0.00022, loss=0.4490
Epoch 444500: lr=0.00022, loss=0.4490
Epoch 445000: lr=0.00022, loss=0.4490
Epoch 445500: lr=0.00022, loss=0.4490
Epoch 446000: lr=0.00022, loss=0.4490
Epoch 446500: lr=0.00022, loss=0.4490
Epoch 447000: lr=0.00022, loss=0.4490
Epoch 447500: lr=0.00022, loss=0.4490
Epoch 448000: lr=0.00022, loss=0.4490
Epoch 448500: lr=0.00022, loss=0.4490
Epoch 449000: lr=0.00022, loss=0.4490
Epoch 449500: lr=0.00022, loss=0.4490
Epoch 450000: lr=0.00022, loss=0.4490
Epoch 450500: lr=0.00022, loss=0.4490
Epoch 451000: lr=0.00022, loss=0.4490
Epoch 451500: lr=0.00022, loss=0.4490
Epoch 452000: lr=0.00022, loss=0.4490
Epoch 452500: lr=0.00022, loss=0.4490
Epoch 453000: lr=0.00022, loss=0.4490
Epoch 453500: lr=0.00022, loss=0.4490
Epoch 454000: lr=0.00022, loss=0.4490
Epoch 454500: lr=0.00022, loss=0.4490
Epoch 455000: lr=0.00022, loss=0.4490
Epoch 455500: lr=0.00022, loss=0.4490
Epoch 456000: lr=0.00022, loss=0.4490
Epoch 456500: lr=0.00022, loss=0.4490
Epoch 457000: lr=0.00022, loss=0.4490
Epoch 457500: lr=0.00022, loss=0.4490

Epoch 458000: lr=0.00022, loss=0.4490
Epoch 458500: lr=0.00022, loss=0.4490
Epoch 459000: lr=0.00022, loss=0.4490
Epoch 459500: lr=0.00022, loss=0.4490
Epoch 460000: lr=0.00022, loss=0.4490
Epoch 460500: lr=0.00022, loss=0.4490
Epoch 461000: lr=0.00022, loss=0.4490
Epoch 461500: lr=0.00022, loss=0.4490
Epoch 462000: lr=0.00022, loss=0.4490
Epoch 462500: lr=0.00022, loss=0.4490
Epoch 463000: lr=0.00022, loss=0.4490
Epoch 463500: lr=0.00022, loss=0.4490
Epoch 464000: lr=0.00022, loss=0.4490
Epoch 464500: lr=0.00021, loss=0.4490
Epoch 465000: lr=0.00021, loss=0.4490
Epoch 465500: lr=0.00021, loss=0.4490
Epoch 466000: lr=0.00021, loss=0.4490
Epoch 466500: lr=0.00021, loss=0.4490
Epoch 467000: lr=0.00021, loss=0.4490
Epoch 467500: lr=0.00021, loss=0.4490
Epoch 468000: lr=0.00021, loss=0.4490
Epoch 468500: lr=0.00021, loss=0.4490
Epoch 469000: lr=0.00021, loss=0.4490
Epoch 469500: lr=0.00021, loss=0.4490
Epoch 470000: lr=0.00021, loss=0.4490
Epoch 470500: lr=0.00021, loss=0.4490
Epoch 471000: lr=0.00021, loss=0.4490
Epoch 471500: lr=0.00021, loss=0.4490
Epoch 472000: lr=0.00021, loss=0.4490
Epoch 472500: lr=0.00021, loss=0.4490
Epoch 473000: lr=0.00021, loss=0.4490
Epoch 473500: lr=0.00021, loss=0.4490
Epoch 474000: lr=0.00021, loss=0.4490
Epoch 474500: lr=0.00021, loss=0.4490
Epoch 475000: lr=0.00021, loss=0.4490
Epoch 475500: lr=0.00021, loss=0.4490
Epoch 476000: lr=0.00021, loss=0.4490
Epoch 476500: lr=0.00021, loss=0.4490
Epoch 477000: lr=0.00021, loss=0.4490
Epoch 477500: lr=0.00021, loss=0.4490
Epoch 478000: lr=0.00021, loss=0.4490
Epoch 478500: lr=0.00021, loss=0.4490
Epoch 479000: lr=0.00021, loss=0.4490
Epoch 479500: lr=0.00021, loss=0.4490
Epoch 480000: lr=0.00021, loss=0.4490
Epoch 480500: lr=0.00021, loss=0.4490
Epoch 481000: lr=0.00021, loss=0.4490
Epoch 481500: lr=0.00021, loss=0.4490
Epoch 482000: lr=0.00021, loss=0.4490
Epoch 482500: lr=0.00021, loss=0.4490
Epoch 483000: lr=0.00021, loss=0.4490
Epoch 483500: lr=0.00021, loss=0.4490
Epoch 484000: lr=0.00021, loss=0.4490
Epoch 484500: lr=0.00021, loss=0.4490
Epoch 485000: lr=0.00021, loss=0.4490
Epoch 485500: lr=0.00021, loss=0.4490
Epoch 486000: lr=0.00021, loss=0.4490
Epoch 486500: lr=0.00021, loss=0.4490
Epoch 487000: lr=0.00020, loss=0.4490
Epoch 487500: lr=0.00020, loss=0.4490
Epoch 488000: lr=0.00020, loss=0.4490
Epoch 488500: lr=0.00020, loss=0.4490
Epoch 489000: lr=0.00020, loss=0.4490
Epoch 489500: lr=0.00020, loss=0.4490
Epoch 490000: lr=0.00020, loss=0.4490
Epoch 490500: lr=0.00020, loss=0.4490
Epoch 491000: lr=0.00020, loss=0.4490
Epoch 491500: lr=0.00020, loss=0.4490
Epoch 492000: lr=0.00020, loss=0.4490
Epoch 492500: lr=0.00020, loss=0.4490
Epoch 493000: lr=0.00020, loss=0.4490
Epoch 493500: lr=0.00020, loss=0.4490
Epoch 494000: lr=0.00020, loss=0.4490
Epoch 494500: lr=0.00020, loss=0.4490
Epoch 495000: lr=0.00020, loss=0.4490
Epoch 495500: lr=0.00020, loss=0.4490
Epoch 496000: lr=0.00020, loss=0.4490
Epoch 496500: lr=0.00020, loss=0.4490
Epoch 497000: lr=0.00020, loss=0.4490
Epoch 497500: lr=0.00020, loss=0.4490
Epoch 498000: lr=0.00020, loss=0.4490
Epoch 498500: lr=0.00020, loss=0.4490
Epoch 499000: lr=0.00020, loss=0.4490
Epoch 499500: lr=0.00020, loss=0.4490
Epoch 500000: lr=0.00020, loss=0.4490
Epoch 500500: lr=0.00020, loss=0.4490
Epoch 501000: lr=0.00020, loss=0.4490
Epoch 501500: lr=0.00020, loss=0.4490
Epoch 502000: lr=0.00020, loss=0.4490
Epoch 502500: lr=0.00020, loss=0.4490
Epoch 503000: lr=0.00020, loss=0.4490
Epoch 503500: lr=0.00020, loss=0.4490
Epoch 504000: lr=0.00020, loss=0.4490
Epoch 504500: lr=0.00020, loss=0.4490
Epoch 505000: lr=0.00020, loss=0.4490
Epoch 505500: lr=0.00020, loss=0.4490
Epoch 506000: lr=0.00020, loss=0.4490
Epoch 506500: lr=0.00020, loss=0.4490
Epoch 507000: lr=0.00020, loss=0.4490
Epoch 507500: lr=0.00020, loss=0.4490
Epoch 508000: lr=0.00020, loss=0.4490
Epoch 508500: lr=0.00020, loss=0.4490
Epoch 509000: lr=0.00020, loss=0.4490
Epoch 509500: lr=0.00020, loss=0.4490
Epoch 510000: lr=0.00020, loss=0.4490
Epoch 510500: lr=0.00020, loss=0.4490
Epoch 511000: lr=0.00020, loss=0.4490
Epoch 511500: lr=0.00020, loss=0.4490
Epoch 512000: lr=0.00019, loss=0.4490
Epoch 512500: lr=0.00019, loss=0.4490
Epoch 513000: lr=0.00019, loss=0.4490
Epoch 513500: lr=0.00019, loss=0.4490
Epoch 514000: lr=0.00019, loss=0.4490
Epoch 514500: lr=0.00019, loss=0.4490
Epoch 515000: lr=0.00019, loss=0.4490
Epoch 515500: lr=0.00019, loss=0.4490
Epoch 516000: lr=0.00019, loss=0.4490
Epoch 516500: lr=0.00019, loss=0.4490
Epoch 517000: lr=0.00019, loss=0.4490
Epoch 517500: lr=0.00019, loss=0.4490
Epoch 518000: lr=0.00019, loss=0.4490
Epoch 518500: lr=0.00019, loss=0.4490
Epoch 519000: lr=0.00019, loss=0.4490
Epoch 519500: lr=0.00019, loss=0.4490
Epoch 520000: lr=0.00019, loss=0.4490
Epoch 520500: lr=0.00019, loss=0.4490
Epoch 521000: lr=0.00019, loss=0.4490
Epoch 521500: lr=0.00019, loss=0.4490
Epoch 522000: lr=0.00019, loss=0.4490
Epoch 522500: lr=0.00019, loss=0.4490
Epoch 523000: lr=0.00019, loss=0.4490
Epoch 523500: lr=0.00019, loss=0.4490
Epoch 524000: lr=0.00019, loss=0.4490
Epoch 524500: lr=0.00019, loss=0.4490
Epoch 525000: lr=0.00019, loss=0.4490
Epoch 525500: lr=0.00019, loss=0.4490
Epoch 526000: lr=0.00019, loss=0.4490
Epoch 526500: lr=0.00019, loss=0.4490
Epoch 527000: lr=0.00019, loss=0.4490
Epoch 527500: lr=0.00019, loss=0.4490
Epoch 528000: lr=0.00019, loss=0.4490
Epoch 528500: lr=0.00019, loss=0.4490
Epoch 529000: lr=0.00019, loss=0.4490
Epoch 529500: lr=0.00019, loss=0.4490
Epoch 530000: lr=0.00019, loss=0.4490
Epoch 530500: lr=0.00019, loss=0.4490
Epoch 531000: lr=0.00019, loss=0.4490
Epoch 531500: lr=0.00019, loss=0.4490
Epoch 532000: lr=0.00019, loss=0.4490
Epoch 532500: lr=0.00019, loss=0.4490
Epoch 533000: lr=0.00019, loss=0.4490
Epoch 533500: lr=0.00019, loss=0.4490
Epoch 534000: lr=0.00019, loss=0.4490
Epoch 534500: lr=0.00019, loss=0.4490
Epoch 535000: lr=0.00019, loss=0.4490
Epoch 535500: lr=0.00019, loss=0.4490
Epoch 536000: lr=0.00019, loss=0.4490
Epoch 536500: lr=0.00019, loss=0.4490
Epoch 537000: lr=0.00019, loss=0.4490
Epoch 537500: lr=0.00019, loss=0.4490
Epoch 538000: lr=0.00019, loss=0.4490
Epoch 538500: lr=0.00019, loss=0.4490
Epoch 539000: lr=0.00019, loss=0.4490
Epoch 539500: lr=0.00019, loss=0.4490
Epoch 540000: lr=0.00018, loss=0.4490
Epoch 540500: lr=0.00018, loss=0.4490
Epoch 541000: lr=0.00018, loss=0.4490
Epoch 541500: lr=0.00018, loss=0.4490
Epoch 542000: lr=0.00018, loss=0.4490
Epoch 542500: lr=0.00018, loss=0.4490
Epoch 543000: lr=0.00018, loss=0.4490
Epoch 543500: lr=0.00018, loss=0.4490
Epoch 544000: lr=0.00018, loss=0.4490
Epoch 544500: lr=0.00018, loss=0.4490
Epoch 545000: lr=0.00018, loss=0.4490
Epoch 545500: lr=0.00018, loss=0.4490
Epoch 546000: lr=0.00018, loss=0.4490
Epoch 546500: lr=0.00018, loss=0.4490
Epoch 547000: lr=0.00018, loss=0.4490
Epoch 547500: lr=0.00018, loss=0.4490
Epoch 548000: lr=0.00018, loss=0.4490
Epoch 548500: lr=0.00018, loss=0.4490
Epoch 549000: lr=0.00018, loss=0.4490
Epoch 549500: lr=0.00018, loss=0.4490
Epoch 550000: lr=0.00018, loss=0.4490
Epoch 550500: lr=0.00018, loss=0.4490
Epoch 551000: lr=0.00018, loss=0.4490
Epoch 551500: lr=0.00018, loss=0.4490
Epoch 552000: lr=0.00018, loss=0.4490
Epoch 552500: lr=0.00018, loss=0.4490
Epoch 553000: lr=0.00018, loss=0.4490
Epoch 553500: lr=0.00018, loss=0.4490
Epoch 554000: lr=0.00018, loss=0.4490
Epoch 554500: lr=0.00018, loss=0.4490
Epoch 555000: lr=0.00018, loss=0.4490
Epoch 555500: lr=0.00018, loss=0.4490
Epoch 556000: lr=0.00018, loss=0.4490
Epoch 556500: lr=0.00018, loss=0.4490
Epoch 557000: lr=0.00018, loss=0.4490
Epoch 557500: lr=0.00018, loss=0.4490
Epoch 558000: lr=0.00018, loss=0.4490
Epoch 558500: lr=0.00018, loss=0.4490
Epoch 559000: lr=0.00018, loss=0.4490
Epoch 559500: lr=0.00018, loss=0.4490
Epoch 560000: lr=0.00018, loss=0.4490
Epoch 560500: lr=0.00018, loss=0.4490
Epoch 561000: lr=0.00018, loss=0.4490
Epoch 561500: lr=0.00018, loss=0.4490
Epoch 562000: lr=0.00018, loss=0.4490
Epoch 562500: lr=0.00018, loss=0.4490
Epoch 563000: lr=0.00018, loss=0.4490
Epoch 563500: lr=0.00018, loss=0.4490
Epoch 564000: lr=0.00018, loss=0.4490
Epoch 564500: lr=0.00018, loss=0.4490
Epoch 565000: lr=0.00018, loss=0.4490
Epoch 565500: lr=0.00018, loss=0.4490
Epoch 566000: lr=0.00018, loss=0.4490
Epoch 566500: lr=0.00018, loss=0.4490
Epoch 567000: lr=0.00018, loss=0.4490
Epoch 567500: lr=0.00018, loss=0.4490
Epoch 568000: lr=0.00018, loss=0.4490
Epoch 568500: lr=0.00018, loss=0.4490
Epoch 569000: lr=0.00018, loss=0.4490
Epoch 569500: lr=0.00018, loss=0.4490
Epoch 570000: lr=0.00018, loss=0.4490
Epoch 570500: lr=0.00017, loss=0.4490
Epoch 571000: lr=0.00017, loss=0.4490
Epoch 571500: lr=0.00017, loss=0.4490
Epoch 572000: lr=0.00017, loss=0.4490
Epoch 572500: lr=0.00017, loss=0.4490

Epoch 573000: lr=0.00017, loss=0.4490
Epoch 573500: lr=0.00017, loss=0.4490
Epoch 574000: lr=0.00017, loss=0.4490
Epoch 574500: lr=0.00017, loss=0.4490
Epoch 575000: lr=0.00017, loss=0.4490
Epoch 575500: lr=0.00017, loss=0.4490
Epoch 576000: lr=0.00017, loss=0.4490
Epoch 576500: lr=0.00017, loss=0.4490
Epoch 577000: lr=0.00017, loss=0.4490
Epoch 577500: lr=0.00017, loss=0.4490
Epoch 578000: lr=0.00017, loss=0.4490
Epoch 578500: lr=0.00017, loss=0.4490
Epoch 579000: lr=0.00017, loss=0.4490
Epoch 579500: lr=0.00017, loss=0.4490
Epoch 580000: lr=0.00017, loss=0.4490
Epoch 580500: lr=0.00017, loss=0.4490
Epoch 581000: lr=0.00017, loss=0.4490
Epoch 581500: lr=0.00017, loss=0.4490
Epoch 582000: lr=0.00017, loss=0.4490
Epoch 582500: lr=0.00017, loss=0.4490
Epoch 583000: lr=0.00017, loss=0.4490
Epoch 583500: lr=0.00017, loss=0.4490
Epoch 584000: lr=0.00017, loss=0.4490
Epoch 584500: lr=0.00017, loss=0.4490
Epoch 585000: lr=0.00017, loss=0.4490
Epoch 585500: lr=0.00017, loss=0.4490
Epoch 586000: lr=0.00017, loss=0.4490
Epoch 586500: lr=0.00017, loss=0.4490
Epoch 587000: lr=0.00017, loss=0.4490
Epoch 587500: lr=0.00017, loss=0.4490
Epoch 588000: lr=0.00017, loss=0.4490
Epoch 588500: lr=0.00017, loss=0.4490
Epoch 589000: lr=0.00017, loss=0.4490
Epoch 589500: lr=0.00017, loss=0.4490
Epoch 590000: lr=0.00017, loss=0.4490
Epoch 590500: lr=0.00017, loss=0.4490
Epoch 591000: lr=0.00017, loss=0.4490
Epoch 591500: lr=0.00017, loss=0.4490
Epoch 592000: lr=0.00017, loss=0.4490
Epoch 592500: lr=0.00017, loss=0.4490
Epoch 593000: lr=0.00017, loss=0.4490
Epoch 593500: lr=0.00017, loss=0.4490
Epoch 594000: lr=0.00017, loss=0.4490
Epoch 594500: lr=0.00017, loss=0.4490
Epoch 595000: lr=0.00017, loss=0.4490
Epoch 595500: lr=0.00017, loss=0.4490
Epoch 596000: lr=0.00017, loss=0.4490
Epoch 596500: lr=0.00017, loss=0.4490
Epoch 597000: lr=0.00017, loss=0.4490
Epoch 597500: lr=0.00017, loss=0.4490
Epoch 598000: lr=0.00017, loss=0.4490
Epoch 598500: lr=0.00017, loss=0.4490
Epoch 599000: lr=0.00017, loss=0.4490
Epoch 599500: lr=0.00017, loss=0.4490
Epoch 600000: lr=0.00017, loss=0.4490
Epoch 600500: lr=0.00017, loss=0.4490
Epoch 601000: lr=0.00017, loss=0.4490
Epoch 601500: lr=0.00017, loss=0.4490
Epoch 602000: lr=0.00017, loss=0.4490
Epoch 602500: lr=0.00017, loss=0.4490
Epoch 603000: lr=0.00017, loss=0.4490
Epoch 603500: lr=0.00017, loss=0.4490
Epoch 604000: lr=0.00017, loss=0.4490
Epoch 604500: lr=0.00017, loss=0.4490
Epoch 605000: lr=0.00017, loss=0.4490
Epoch 605500: lr=0.00016, loss=0.4490
Epoch 606000: lr=0.00016, loss=0.4490
Epoch 606500: lr=0.00016, loss=0.4490
Epoch 607000: lr=0.00016, loss=0.4490
Epoch 607500: lr=0.00016, loss=0.4490
Epoch 608000: lr=0.00016, loss=0.4490
Epoch 608500: lr=0.00016, loss=0.4490
Epoch 609000: lr=0.00016, loss=0.4490
Epoch 609500: lr=0.00016, loss=0.4490
Epoch 610000: lr=0.00016, loss=0.4490
Epoch 610500: lr=0.00016, loss=0.4490
Epoch 611000: lr=0.00016, loss=0.4490
Epoch 611500: lr=0.00016, loss=0.4490
Epoch 612000: lr=0.00016, loss=0.4490
Epoch 612500: lr=0.00016, loss=0.4490
Epoch 613000: lr=0.00016, loss=0.4490
Epoch 613500: lr=0.00016, loss=0.4490
Epoch 614000: lr=0.00016, loss=0.4490
Epoch 614500: lr=0.00016, loss=0.4490
Epoch 615000: lr=0.00016, loss=0.4490
Epoch 615500: lr=0.00016, loss=0.4490
Epoch 616000: lr=0.00016, loss=0.4490
Epoch 616500: lr=0.00016, loss=0.4490
Epoch 617000: lr=0.00016, loss=0.4490
Epoch 617500: lr=0.00016, loss=0.4490
Epoch 618000: lr=0.00016, loss=0.4490
Epoch 618500: lr=0.00016, loss=0.4490
Epoch 619000: lr=0.00016, loss=0.4490
Epoch 619500: lr=0.00016, loss=0.4490
Epoch 620000: lr=0.00016, loss=0.4490
Epoch 620500: lr=0.00016, loss=0.4490
Epoch 621000: lr=0.00016, loss=0.4490
Epoch 621500: lr=0.00016, loss=0.4490
Epoch 622000: lr=0.00016, loss=0.4490
Epoch 622500: lr=0.00016, loss=0.4490
Epoch 623000: lr=0.00016, loss=0.4490
Epoch 623500: lr=0.00016, loss=0.4490
Epoch 624000: lr=0.00016, loss=0.4490
Epoch 624500: lr=0.00016, loss=0.4490
Epoch 625000: lr=0.00016, loss=0.4490
Epoch 625500: lr=0.00016, loss=0.4490
Epoch 626000: lr=0.00016, loss=0.4490
Epoch 626500: lr=0.00016, loss=0.4490
Epoch 627000: lr=0.00016, loss=0.4490
Epoch 627500: lr=0.00016, loss=0.4490
Epoch 628000: lr=0.00016, loss=0.4490
Epoch 628500: lr=0.00016, loss=0.4490
Epoch 629000: lr=0.00016, loss=0.4490
Epoch 629500: lr=0.00016, loss=0.4490
Epoch 630000: lr=0.00016, loss=0.4490
Epoch 630500: lr=0.00016, loss=0.4490
Epoch 631000: lr=0.00016, loss=0.4490
Epoch 631500: lr=0.00016, loss=0.4490
Epoch 632000: lr=0.00016, loss=0.4490
Epoch 632500: lr=0.00016, loss=0.4490
Epoch 633000: lr=0.00016, loss=0.4490
Epoch 633500: lr=0.00016, loss=0.4490
Epoch 634000: lr=0.00016, loss=0.4490
Epoch 634500: lr=0.00016, loss=0.4490
Epoch 635000: lr=0.00016, loss=0.4490
Epoch 635500: lr=0.00016, loss=0.4490
Epoch 636000: lr=0.00016, loss=0.4490
Epoch 636500: lr=0.00016, loss=0.4490
Epoch 637000: lr=0.00016, loss=0.4490
Epoch 637500: lr=0.00016, loss=0.4490
Epoch 638000: lr=0.00016, loss=0.4490
Epoch 638500: lr=0.00016, loss=0.4490
Epoch 639000: lr=0.00016, loss=0.4490
Epoch 639500: lr=0.00016, loss=0.4490
Epoch 640000: lr=0.00016, loss=0.4490
Epoch 640500: lr=0.00016, loss=0.4490
Epoch 641000: lr=0.00016, loss=0.4490
Epoch 641500: lr=0.00016, loss=0.4490
Epoch 642000: lr=0.00016, loss=0.4490
Epoch 642500: lr=0.00016, loss=0.4490
Epoch 643000: lr=0.00016, loss=0.4490
Epoch 643500: lr=0.00016, loss=0.4490
Epoch 644000: lr=0.00016, loss=0.4490
Epoch 644500: lr=0.00015, loss=0.4490
Epoch 645000: lr=0.00015, loss=0.4490
Epoch 645500: lr=0.00015, loss=0.4490
Epoch 646000: lr=0.00015, loss=0.4490
Epoch 646500: lr=0.00015, loss=0.4490
Epoch 647000: lr=0.00015, loss=0.4490
Epoch 647500: lr=0.00015, loss=0.4490
Epoch 648000: lr=0.00015, loss=0.4490
Epoch 648500: lr=0.00015, loss=0.4490
Epoch 649000: lr=0.00015, loss=0.4490
Epoch 649500: lr=0.00015, loss=0.4490
Epoch 650000: lr=0.00015, loss=0.4490
Epoch 650500: lr=0.00015, loss=0.4490
Epoch 651000: lr=0.00015, loss=0.4490
Epoch 651500: lr=0.00015, loss=0.4490
Epoch 652000: lr=0.00015, loss=0.4490
Epoch 652500: lr=0.00015, loss=0.4490
Epoch 653000: lr=0.00015, loss=0.4490
Epoch 653500: lr=0.00015, loss=0.4490
Epoch 654000: lr=0.00015, loss=0.4490
Epoch 654500: lr=0.00015, loss=0.4490
Epoch 655000: lr=0.00015, loss=0.4490
Epoch 655500: lr=0.00015, loss=0.4490
Epoch 656000: lr=0.00015, loss=0.4490
Epoch 656500: lr=0.00015, loss=0.4490
Epoch 657000: lr=0.00015, loss=0.4490
Epoch 657500: lr=0.00015, loss=0.4490
Epoch 658000: lr=0.00015, loss=0.4490
Epoch 658500: lr=0.00015, loss=0.4490
Epoch 659000: lr=0.00015, loss=0.4490
Epoch 659500: lr=0.00015, loss=0.4490
Epoch 660000: lr=0.00015, loss=0.4490
Epoch 660500: lr=0.00015, loss=0.4490
Epoch 661000: lr=0.00015, loss=0.4490
Epoch 661500: lr=0.00015, loss=0.4490
Epoch 662000: lr=0.00015, loss=0.4490
Epoch 662500: lr=0.00015, loss=0.4490
Epoch 663000: lr=0.00015, loss=0.4490
Epoch 663500: lr=0.00015, loss=0.4490
Epoch 664000: lr=0.00015, loss=0.4490
Epoch 664500: lr=0.00015, loss=0.4490
Epoch 665000: lr=0.00015, loss=0.4490
Epoch 665500: lr=0.00015, loss=0.4490
Epoch 666000: lr=0.00015, loss=0.4490
Epoch 666500: lr=0.00015, loss=0.4490
Epoch 667000: lr=0.00015, loss=0.4490
Epoch 667500: lr=0.00015, loss=0.4490
Epoch 668000: lr=0.00015, loss=0.4490
Epoch 668500: lr=0.00015, loss=0.4490
Epoch 669000: lr=0.00015, loss=0.4490
Epoch 669500: lr=0.00015, loss=0.4490
Epoch 670000: lr=0.00015, loss=0.4490
Epoch 670500: lr=0.00015, loss=0.4490
Epoch 671000: lr=0.00015, loss=0.4490
Epoch 671500: lr=0.00015, loss=0.4490
Epoch 672000: lr=0.00015, loss=0.4490
Epoch 672500: lr=0.00015, loss=0.4490
Epoch 673000: lr=0.00015, loss=0.4490
Epoch 673500: lr=0.00015, loss=0.4490
Epoch 674000: lr=0.00015, loss=0.4490
Epoch 674500: lr=0.00015, loss=0.4490
Epoch 675000: lr=0.00015, loss=0.4490
Epoch 675500: lr=0.00015, loss=0.4490
Epoch 676000: lr=0.00015, loss=0.4490
Epoch 676500: lr=0.00015, loss=0.4490
Epoch 677000: lr=0.00015, loss=0.4490
Epoch 677500: lr=0.00015, loss=0.4490
Epoch 678000: lr=0.00015, loss=0.4490
Epoch 678500: lr=0.00015, loss=0.4490
Epoch 679000: lr=0.00015, loss=0.4490
Epoch 679500: lr=0.00015, loss=0.4490
Epoch 680000: lr=0.00015, loss=0.4490
Epoch 680500: lr=0.00015, loss=0.4490
Epoch 681000: lr=0.00015, loss=0.4490
Epoch 681500: lr=0.00015, loss=0.4490
Epoch 682000: lr=0.00015, loss=0.4490
Epoch 682500: lr=0.00015, loss=0.4490
Epoch 683000: lr=0.00015, loss=0.4490
Epoch 683500: lr=0.00015, loss=0.4490
Epoch 684000: lr=0.00015, loss=0.4490
Epoch 684500: lr=0.00015, loss=0.4490

Epoch 685000: lr=0.00015, loss=0.4490
Epoch 685500: lr=0.00015, loss=0.4490
Epoch 686000: lr=0.00015, loss=0.4490
Epoch 686500: lr=0.00015, loss=0.4490
Epoch 687000: lr=0.00015, loss=0.4490
Epoch 687500: lr=0.00015, loss=0.4490
Epoch 688000: lr=0.00015, loss=0.4490
Epoch 688500: lr=0.00015, loss=0.4490
Epoch 689000: lr=0.00014, loss=0.4490
Epoch 689500: lr=0.00014, loss=0.4490
Epoch 690000: lr=0.00014, loss=0.4490
Epoch 690500: lr=0.00014, loss=0.4490
Epoch 691000: lr=0.00014, loss=0.4490
Epoch 691500: lr=0.00014, loss=0.4490
Epoch 692000: lr=0.00014, loss=0.4490
Epoch 692500: lr=0.00014, loss=0.4490
Epoch 693000: lr=0.00014, loss=0.4490
Epoch 693500: lr=0.00014, loss=0.4490
Epoch 694000: lr=0.00014, loss=0.4490
Epoch 694500: lr=0.00014, loss=0.4490
Epoch 695000: lr=0.00014, loss=0.4490
Epoch 695500: lr=0.00014, loss=0.4490
Epoch 696000: lr=0.00014, loss=0.4490
Epoch 696500: lr=0.00014, loss=0.4490
Epoch 697000: lr=0.00014, loss=0.4490
Epoch 697500: lr=0.00014, loss=0.4490
Epoch 698000: lr=0.00014, loss=0.4490
Epoch 698500: lr=0.00014, loss=0.4490
Epoch 699000: lr=0.00014, loss=0.4490
Epoch 699500: lr=0.00014, loss=0.4490
Epoch 700000: lr=0.00014, loss=0.4490
Epoch 700500: lr=0.00014, loss=0.4490
Epoch 701000: lr=0.00014, loss=0.4490
Epoch 701500: lr=0.00014, loss=0.4490
Epoch 702000: lr=0.00014, loss=0.4490
Epoch 702500: lr=0.00014, loss=0.4490
Epoch 703000: lr=0.00014, loss=0.4490
Epoch 703500: lr=0.00014, loss=0.4490
Epoch 704000: lr=0.00014, loss=0.4490
Epoch 704500: lr=0.00014, loss=0.4490
Epoch 705000: lr=0.00014, loss=0.4490
Epoch 705500: lr=0.00014, loss=0.4490
Epoch 706000: lr=0.00014, loss=0.4490
Epoch 706500: lr=0.00014, loss=0.4490
Epoch 707000: lr=0.00014, loss=0.4490
Epoch 707500: lr=0.00014, loss=0.4490
Epoch 708000: lr=0.00014, loss=0.4490
Epoch 708500: lr=0.00014, loss=0.4490
Epoch 709000: lr=0.00014, loss=0.4490
Epoch 709500: lr=0.00014, loss=0.4490
Epoch 710000: lr=0.00014, loss=0.4490
Epoch 710500: lr=0.00014, loss=0.4490
Epoch 711000: lr=0.00014, loss=0.4490
Epoch 711500: lr=0.00014, loss=0.4490
Epoch 712000: lr=0.00014, loss=0.4490
Epoch 712500: lr=0.00014, loss=0.4490
Epoch 713000: lr=0.00014, loss=0.4490
Epoch 713500: lr=0.00014, loss=0.4490
Epoch 714000: lr=0.00014, loss=0.4490
Epoch 714500: lr=0.00014, loss=0.4490
Epoch 715000: lr=0.00014, loss=0.4490
Epoch 715500: lr=0.00014, loss=0.4490
Epoch 716000: lr=0.00014, loss=0.4490
Epoch 716500: lr=0.00014, loss=0.4490
Epoch 717000: lr=0.00014, loss=0.4490
Epoch 717500: lr=0.00014, loss=0.4490
Epoch 718000: lr=0.00014, loss=0.4490
Epoch 718500: lr=0.00014, loss=0.4490
Epoch 719000: lr=0.00014, loss=0.4490
Epoch 719500: lr=0.00014, loss=0.4490
Epoch 720000: lr=0.00014, loss=0.4490
Epoch 720500: lr=0.00014, loss=0.4490
Epoch 721000: lr=0.00014, loss=0.4490
Epoch 721500: lr=0.00014, loss=0.4490
Epoch 722000: lr=0.00014, loss=0.4490
Epoch 722500: lr=0.00014, loss=0.4490
Epoch 723000: lr=0.00014, loss=0.4490
Epoch 723500: lr=0.00014, loss=0.4490
Epoch 724000: lr=0.00014, loss=0.4490
Epoch 724500: lr=0.00014, loss=0.4490
Epoch 725000: lr=0.00014, loss=0.4490
Epoch 725500: lr=0.00014, loss=0.4490
Epoch 726000: lr=0.00014, loss=0.4490
Epoch 726500: lr=0.00014, loss=0.4490
Epoch 727000: lr=0.00014, loss=0.4490
Epoch 727500: lr=0.00014, loss=0.4490
Epoch 728000: lr=0.00014, loss=0.4490
Epoch 728500: lr=0.00014, loss=0.4490
Epoch 729000: lr=0.00014, loss=0.4490
Epoch 729500: lr=0.00014, loss=0.4490
Epoch 730000: lr=0.00014, loss=0.4490
Epoch 730500: lr=0.00014, loss=0.4490
Epoch 731000: lr=0.00014, loss=0.4490
Epoch 731500: lr=0.00014, loss=0.4490
Epoch 732000: lr=0.00014, loss=0.4490
Epoch 732500: lr=0.00014, loss=0.4490
Epoch 733000: lr=0.00014, loss=0.4490
Epoch 733500: lr=0.00014, loss=0.4490
Epoch 734000: lr=0.00014, loss=0.4490
Epoch 734500: lr=0.00014, loss=0.4490
Epoch 735000: lr=0.00014, loss=0.4490
Epoch 735500: lr=0.00014, loss=0.4490
Epoch 736000: lr=0.00014, loss=0.4490
Epoch 736500: lr=0.00014, loss=0.4490
Epoch 737000: lr=0.00014, loss=0.4490
Epoch 737500: lr=0.00014, loss=0.4490
Epoch 738000: lr=0.00014, loss=0.4490
Epoch 738500: lr=0.00014, loss=0.4490
Epoch 739000: lr=0.00014, loss=0.4490
Epoch 739500: lr=0.00014, loss=0.4490
Epoch 740000: lr=0.00013, loss=0.4490
Epoch 740500: lr=0.00013, loss=0.4490
Epoch 741000: lr=0.00013, loss=0.4490
Epoch 741500: lr=0.00013, loss=0.4490
Epoch 742000: lr=0.00013, loss=0.4490
Epoch 742500: lr=0.00013, loss=0.4490
Epoch 743000: lr=0.00013, loss=0.4490
Epoch 743500: lr=0.00013, loss=0.4490
Epoch 744000: lr=0.00013, loss=0.4490
Epoch 744500: lr=0.00013, loss=0.4490
Epoch 745000: lr=0.00013, loss=0.4490
Epoch 745500: lr=0.00013, loss=0.4490
Epoch 746000: lr=0.00013, loss=0.4490
Epoch 746500: lr=0.00013, loss=0.4490
Epoch 747000: lr=0.00013, loss=0.4490
Epoch 747500: lr=0.00013, loss=0.4490
Epoch 748000: lr=0.00013, loss=0.4490
Epoch 748500: lr=0.00013, loss=0.4490
Epoch 749000: lr=0.00013, loss=0.4490
Epoch 749500: lr=0.00013, loss=0.4490
Epoch 750000: lr=0.00013, loss=0.4490
Epoch 750500: lr=0.00013, loss=0.4490
Epoch 751000: lr=0.00013, loss=0.4490
Epoch 751500: lr=0.00013, loss=0.4490
Epoch 752000: lr=0.00013, loss=0.4490
Epoch 752500: lr=0.00013, loss=0.4490
Epoch 753000: lr=0.00013, loss=0.4490
Epoch 753500: lr=0.00013, loss=0.4490
Epoch 754000: lr=0.00013, loss=0.4490
Epoch 754500: lr=0.00013, loss=0.4490
Epoch 755000: lr=0.00013, loss=0.4490
Epoch 755500: lr=0.00013, loss=0.4490
Epoch 756000: lr=0.00013, loss=0.4490
Epoch 756500: lr=0.00013, loss=0.4490
Epoch 757000: lr=0.00013, loss=0.4490
Epoch 757500: lr=0.00013, loss=0.4490
Epoch 758000: lr=0.00013, loss=0.4490
Epoch 758500: lr=0.00013, loss=0.4490
Epoch 759000: lr=0.00013, loss=0.4490
Epoch 759500: lr=0.00013, loss=0.4490
Epoch 760000: lr=0.00013, loss=0.4490
Epoch 760500: lr=0.00013, loss=0.4490
Epoch 761000: lr=0.00013, loss=0.4490
Epoch 761500: lr=0.00013, loss=0.4490
Epoch 762000: lr=0.00013, loss=0.4490
Epoch 762500: lr=0.00013, loss=0.4490
Epoch 763000: lr=0.00013, loss=0.4490
Epoch 763500: lr=0.00013, loss=0.4490
Epoch 764000: lr=0.00013, loss=0.4490
Epoch 764500: lr=0.00013, loss=0.4490
Epoch 765000: lr=0.00013, loss=0.4490
Epoch 765500: lr=0.00013, loss=0.4490
Epoch 766000: lr=0.00013, loss=0.4490
Epoch 766500: lr=0.00013, loss=0.4490
Epoch 767000: lr=0.00013, loss=0.4490
Epoch 767500: lr=0.00013, loss=0.4490
Epoch 768000: lr=0.00013, loss=0.4490
Epoch 768500: lr=0.00013, loss=0.4490
Epoch 769000: lr=0.00013, loss=0.4490
Epoch 769500: lr=0.00013, loss=0.4490
Epoch 770000: lr=0.00013, loss=0.4490
Epoch 770500: lr=0.00013, loss=0.4490
Epoch 771000: lr=0.00013, loss=0.4490
Epoch 771500: lr=0.00013, loss=0.4490
Epoch 772000: lr=0.00013, loss=0.4490
Epoch 772500: lr=0.00013, loss=0.4490
Epoch 773000: lr=0.00013, loss=0.4490
Epoch 773500: lr=0.00013, loss=0.4490
Epoch 774000: lr=0.00013, loss=0.4490
Epoch 774500: lr=0.00013, loss=0.4490
Epoch 775000: lr=0.00013, loss=0.4490
Epoch 775500: lr=0.00013, loss=0.4490
Epoch 776000: lr=0.00013, loss=0.4490
Epoch 776500: lr=0.00013, loss=0.4490
Epoch 777000: lr=0.00013, loss=0.4490
Epoch 777500: lr=0.00013, loss=0.4490
Epoch 778000: lr=0.00013, loss=0.4490
Epoch 778500: lr=0.00013, loss=0.4490
Epoch 779000: lr=0.00013, loss=0.4490
Epoch 779500: lr=0.00013, loss=0.4490
Epoch 780000: lr=0.00013, loss=0.4490
Epoch 780500: lr=0.00013, loss=0.4490
Epoch 781000: lr=0.00013, loss=0.4490
Epoch 781500: lr=0.00013, loss=0.4490
Epoch 782000: lr=0.00013, loss=0.4490
Epoch 782500: lr=0.00013, loss=0.4490
Epoch 783000: lr=0.00013, loss=0.4490
Epoch 783500: lr=0.00013, loss=0.4490
Epoch 784000: lr=0.00013, loss=0.4490
Epoch 784500: lr=0.00013, loss=0.4490
Epoch 785000: lr=0.00013, loss=0.4490
Epoch 785500: lr=0.00013, loss=0.4490
Epoch 786000: lr=0.00013, loss=0.4490
Epoch 786500: lr=0.00013, loss=0.4490
Epoch 787000: lr=0.00013, loss=0.4490
Epoch 787500: lr=0.00013, loss=0.4490
Epoch 788000: lr=0.00013, loss=0.4490
Epoch 788500: lr=0.00013, loss=0.4490
Epoch 789000: lr=0.00013, loss=0.4490
Epoch 789500: lr=0.00013, loss=0.4490
Epoch 790000: lr=0.00013, loss=0.4490
Epoch 790500: lr=0.00013, loss=0.4490
Epoch 791000: lr=0.00013, loss=0.4490
Epoch 791500: lr=0.00013, loss=0.4490
Epoch 792000: lr=0.00013, loss=0.4490
Epoch 792500: lr=0.00013, loss=0.4490
Epoch 793000: lr=0.00013, loss=0.4490
Epoch 793500: lr=0.00013, loss=0.4490
Epoch 794000: lr=0.00013, loss=0.4490
Epoch 794500: lr=0.00013, loss=0.4490
Epoch 795000: lr=0.00013, loss=0.4490
Epoch 795500: lr=0.00013, loss=0.4490
Epoch 796000: lr=0.00013, loss=0.4490
Epoch 796500: lr=0.00013, loss=0.4490
Epoch 797000: lr=0.00013, loss=0.4490

Epoch 797500: lr=0.00013, loss=0.4490
Epoch 798000: lr=0.00013, loss=0.4490
Epoch 798500: lr=0.00013, loss=0.4490
Epoch 799000: lr=0.00013, loss=0.4490
Epoch 799500: lr=0.00012, loss=0.4490
Epoch 800000: lr=0.00012, loss=0.4490
Epoch 800500: lr=0.00012, loss=0.4490
Epoch 801000: lr=0.00012, loss=0.4490
Epoch 801500: lr=0.00012, loss=0.4490
Epoch 802000: lr=0.00012, loss=0.4490
Epoch 802500: lr=0.00012, loss=0.4490
Epoch 803000: lr=0.00012, loss=0.4490
Epoch 803500: lr=0.00012, loss=0.4490
Epoch 804000: lr=0.00012, loss=0.4490
Epoch 804500: lr=0.00012, loss=0.4490
Epoch 805000: lr=0.00012, loss=0.4490
Epoch 805500: lr=0.00012, loss=0.4490
Epoch 806000: lr=0.00012, loss=0.4490
Epoch 806500: lr=0.00012, loss=0.4490
Epoch 807000: lr=0.00012, loss=0.4490
Epoch 807500: lr=0.00012, loss=0.4490
Epoch 808000: lr=0.00012, loss=0.4490
Epoch 808500: lr=0.00012, loss=0.4490
Epoch 809000: lr=0.00012, loss=0.4490
Epoch 809500: lr=0.00012, loss=0.4490
Epoch 810000: lr=0.00012, loss=0.4490
Epoch 810500: lr=0.00012, loss=0.4490
Epoch 811000: lr=0.00012, loss=0.4490
Epoch 811500: lr=0.00012, loss=0.4490
Epoch 812000: lr=0.00012, loss=0.4490
Epoch 812500: lr=0.00012, loss=0.4490
Epoch 813000: lr=0.00012, loss=0.4490
Epoch 813500: lr=0.00012, loss=0.4490
Epoch 814000: lr=0.00012, loss=0.4490
Epoch 814500: lr=0.00012, loss=0.4490
Epoch 815000: lr=0.00012, loss=0.4490
Epoch 815500: lr=0.00012, loss=0.4490
Epoch 816000: lr=0.00012, loss=0.4490
Epoch 816500: lr=0.00012, loss=0.4490
Epoch 817000: lr=0.00012, loss=0.4490
Epoch 817500: lr=0.00012, loss=0.4490
Epoch 818000: lr=0.00012, loss=0.4490
Epoch 818500: lr=0.00012, loss=0.4490
Epoch 819000: lr=0.00012, loss=0.4490
Epoch 819500: lr=0.00012, loss=0.4490
Epoch 820000: lr=0.00012, loss=0.4490
Epoch 820500: lr=0.00012, loss=0.4490
Epoch 821000: lr=0.00012, loss=0.4490
Epoch 821500: lr=0.00012, loss=0.4490
Epoch 822000: lr=0.00012, loss=0.4490
Epoch 822500: lr=0.00012, loss=0.4490
Epoch 823000: lr=0.00012, loss=0.4490
Epoch 823500: lr=0.00012, loss=0.4490
Epoch 824000: lr=0.00012, loss=0.4490
Epoch 824500: lr=0.00012, loss=0.4490
Epoch 825000: lr=0.00012, loss=0.4490
Epoch 825500: lr=0.00012, loss=0.4490
Epoch 826000: lr=0.00012, loss=0.4490
Epoch 826500: lr=0.00012, loss=0.4490
Epoch 827000: lr=0.00012, loss=0.4490
Epoch 827500: lr=0.00012, loss=0.4490
Epoch 828000: lr=0.00012, loss=0.4490
Epoch 828500: lr=0.00012, loss=0.4490
Epoch 829000: lr=0.00012, loss=0.4490
Epoch 829500: lr=0.00012, loss=0.4490
Epoch 830000: lr=0.00012, loss=0.4490
Epoch 830500: lr=0.00012, loss=0.4490
Epoch 831000: lr=0.00012, loss=0.4490
Epoch 831500: lr=0.00012, loss=0.4490
Epoch 832000: lr=0.00012, loss=0.4490
Epoch 832500: lr=0.00012, loss=0.4490
Epoch 833000: lr=0.00012, loss=0.4490
Epoch 833500: lr=0.00012, loss=0.4490
Epoch 834000: lr=0.00012, loss=0.4490
Epoch 834500: lr=0.00012, loss=0.4490
Epoch 835000: lr=0.00012, loss=0.4490
Epoch 835500: lr=0.00012, loss=0.4490
Epoch 836000: lr=0.00012, loss=0.4490
Epoch 836500: lr=0.00012, loss=0.4490
Epoch 837000: lr=0.00012, loss=0.4490
Epoch 837500: lr=0.00012, loss=0.4490
Epoch 838000: lr=0.00012, loss=0.4490
Epoch 838500: lr=0.00012, loss=0.4490
Epoch 839000: lr=0.00012, loss=0.4490
Epoch 839500: lr=0.00012, loss=0.4490
Epoch 840000: lr=0.00012, loss=0.4490
Epoch 840500: lr=0.00012, loss=0.4490
Epoch 841000: lr=0.00012, loss=0.4490
Epoch 841500: lr=0.00012, loss=0.4490
Epoch 842000: lr=0.00012, loss=0.4490
Epoch 842500: lr=0.00012, loss=0.4490
Epoch 843000: lr=0.00012, loss=0.4490
Epoch 843500: lr=0.00012, loss=0.4490
Epoch 844000: lr=0.00012, loss=0.4490
Epoch 844500: lr=0.00012, loss=0.4490
Epoch 845000: lr=0.00012, loss=0.4490
Epoch 845500: lr=0.00012, loss=0.4490
Epoch 846000: lr=0.00012, loss=0.4490
Epoch 846500: lr=0.00012, loss=0.4490
Epoch 847000: lr=0.00012, loss=0.4490
Epoch 847500: lr=0.00012, loss=0.4490
Epoch 848000: lr=0.00012, loss=0.4490
Epoch 848500: lr=0.00012, loss=0.4490
Epoch 849000: lr=0.00012, loss=0.4490
Epoch 849500: lr=0.00012, loss=0.4490
Epoch 850000: lr=0.00012, loss=0.4490
Epoch 850500: lr=0.00012, loss=0.4490
Epoch 851000: lr=0.00012, loss=0.4490
Epoch 851500: lr=0.00012, loss=0.4490
Epoch 852000: lr=0.00012, loss=0.4490
Epoch 852500: lr=0.00012, loss=0.4490
Epoch 853000: lr=0.00012, loss=0.4490
Epoch 853500: lr=0.00012, loss=0.4490
Epoch 854000: lr=0.00012, loss=0.4490
Epoch 854500: lr=0.00012, loss=0.4490
Epoch 855000: lr=0.00012, loss=0.4490
Epoch 855500: lr=0.00012, loss=0.4490
Epoch 856000: lr=0.00012, loss=0.4490
Epoch 856500: lr=0.00012, loss=0.4490
Epoch 857000: lr=0.00012, loss=0.4490
Epoch 857500: lr=0.00012, loss=0.4490
Epoch 858000: lr=0.00012, loss=0.4490
Epoch 858500: lr=0.00012, loss=0.4490
Epoch 859000: lr=0.00012, loss=0.4490
Epoch 859500: lr=0.00012, loss=0.4490
Epoch 860000: lr=0.00012, loss=0.4490
Epoch 860500: lr=0.00012, loss=0.4490
Epoch 861000: lr=0.00012, loss=0.4490
Epoch 861500: lr=0.00012, loss=0.4490
Epoch 862000: lr=0.00012, loss=0.4490
Epoch 862500: lr=0.00012, loss=0.4490
Epoch 863000: lr=0.00012, loss=0.4490
Epoch 863500: lr=0.00012, loss=0.4490
Epoch 864000: lr=0.00012, loss=0.4490
Epoch 864500: lr=0.00012, loss=0.4490
Epoch 865000: lr=0.00012, loss=0.4490
Epoch 865500: lr=0.00012, loss=0.4490
Epoch 866000: lr=0.00012, loss=0.4490
Epoch 866500: lr=0.00012, loss=0.4490
Epoch 867000: lr=0.00012, loss=0.4490
Epoch 867500: lr=0.00012, loss=0.4490
Epoch 868000: lr=0.00012, loss=0.4490
Epoch 868500: lr=0.00012, loss=0.4490
Epoch 869000: lr=0.00011, loss=0.4490
Epoch 869500: lr=0.00011, loss=0.4490
Epoch 870000: lr=0.00011, loss=0.4490
Epoch 870500: lr=0.00011, loss=0.4490
Epoch 871000: lr=0.00011, loss=0.4490
Epoch 871500: lr=0.00011, loss=0.4490
Epoch 872000: lr=0.00011, loss=0.4490
Epoch 872500: lr=0.00011, loss=0.4490
Epoch 873000: lr=0.00011, loss=0.4490
Epoch 873500: lr=0.00011, loss=0.4490
Epoch 874000: lr=0.00011, loss=0.4490
Epoch 874500: lr=0.00011, loss=0.4490
Epoch 875000: lr=0.00011, loss=0.4490
Epoch 875500: lr=0.00011, loss=0.4490
Epoch 876000: lr=0.00011, loss=0.4490
Epoch 876500: lr=0.00011, loss=0.4490
Epoch 877000: lr=0.00011, loss=0.4490
Epoch 877500: lr=0.00011, loss=0.4490
Epoch 878000: lr=0.00011, loss=0.4490
Epoch 878500: lr=0.00011, loss=0.4490
Epoch 879000: lr=0.00011, loss=0.4490
Epoch 879500: lr=0.00011, loss=0.4490
Epoch 880000: lr=0.00011, loss=0.4490
Epoch 880500: lr=0.00011, loss=0.4490
Epoch 881000: lr=0.00011, loss=0.4490
Epoch 881500: lr=0.00011, loss=0.4490
Epoch 882000: lr=0.00011, loss=0.4490
Epoch 882500: lr=0.00011, loss=0.4490
Epoch 883000: lr=0.00011, loss=0.4490
Epoch 883500: lr=0.00011, loss=0.4490
Epoch 884000: lr=0.00011, loss=0.4490
Epoch 884500: lr=0.00011, loss=0.4490
Epoch 885000: lr=0.00011, loss=0.4490
Epoch 885500: lr=0.00011, loss=0.4490
Epoch 886000: lr=0.00011, loss=0.4490
Epoch 886500: lr=0.00011, loss=0.4490
Epoch 887000: lr=0.00011, loss=0.4490
Epoch 887500: lr=0.00011, loss=0.4490
Epoch 888000: lr=0.00011, loss=0.4490
Epoch 888500: lr=0.00011, loss=0.4490
Epoch 889000: lr=0.00011, loss=0.4490
Epoch 889500: lr=0.00011, loss=0.4490
Epoch 890000: lr=0.00011, loss=0.4490
Epoch 890500: lr=0.00011, loss=0.4490
Epoch 891000: lr=0.00011, loss=0.4490
Epoch 891500: lr=0.00011, loss=0.4490
Epoch 892000: lr=0.00011, loss=0.4490
Epoch 892500: lr=0.00011, loss=0.4490
Epoch 893000: lr=0.00011, loss=0.4490
Epoch 893500: lr=0.00011, loss=0.4490
Epoch 894000: lr=0.00011, loss=0.4490
Epoch 894500: lr=0.00011, loss=0.4490
Epoch 895000: lr=0.00011, loss=0.4490
Epoch 895500: lr=0.00011, loss=0.4490
Epoch 896000: lr=0.00011, loss=0.4490
Epoch 896500: lr=0.00011, loss=0.4490
Epoch 897000: lr=0.00011, loss=0.4490
Epoch 897500: lr=0.00011, loss=0.4490
Epoch 898000: lr=0.00011, loss=0.4490
Epoch 898500: lr=0.00011, loss=0.4490
Epoch 899000: lr=0.00011, loss=0.4490
Epoch 899500: lr=0.00011, loss=0.4490
Epoch 900000: lr=0.00011, loss=0.4490
Epoch 900500: lr=0.00011, loss=0.4490
Epoch 901000: lr=0.00011, loss=0.4490
Epoch 901500: lr=0.00011, loss=0.4490
Epoch 902000: lr=0.00011, loss=0.4490
Epoch 902500: lr=0.00011, loss=0.4490
Epoch 903000: lr=0.00011, loss=0.4490
Epoch 903500: lr=0.00011, loss=0.4490
Epoch 904000: lr=0.00011, loss=0.4490
Epoch 904500: lr=0.00011, loss=0.4490
Epoch 905000: lr=0.00011, loss=0.4490
Epoch 905500: lr=0.00011, loss=0.4490
Epoch 906000: lr=0.00011, loss=0.4490
Epoch 906500: lr=0.00011, loss=0.4490
Epoch 907000: lr=0.00011, loss=0.4490
Epoch 907500: lr=0.00011, loss=0.4490
Epoch 908000: lr=0.00011, loss=0.4490

Epoch 908500: lr=0.00011, loss=0.4490
Epoch 909000: lr=0.00011, loss=0.4490
Epoch 909500: lr=0.00011, loss=0.4490
Epoch 910000: lr=0.00011, loss=0.4490
Epoch 910500: lr=0.00011, loss=0.4490
Epoch 911000: lr=0.00011, loss=0.4490
Epoch 911500: lr=0.00011, loss=0.4490
Epoch 912000: lr=0.00011, loss=0.4490
Epoch 912500: lr=0.00011, loss=0.4490
Epoch 913000: lr=0.00011, loss=0.4490
Epoch 913500: lr=0.00011, loss=0.4490
Epoch 914000: lr=0.00011, loss=0.4490
Epoch 914500: lr=0.00011, loss=0.4490
Epoch 915000: lr=0.00011, loss=0.4490
Epoch 915500: lr=0.00011, loss=0.4490
Epoch 916000: lr=0.00011, loss=0.4490
Epoch 916500: lr=0.00011, loss=0.4490
Epoch 917000: lr=0.00011, loss=0.4490
Epoch 917500: lr=0.00011, loss=0.4490
Epoch 918000: lr=0.00011, loss=0.4490
Epoch 918500: lr=0.00011, loss=0.4490
Epoch 919000: lr=0.00011, loss=0.4490
Epoch 919500: lr=0.00011, loss=0.4490
Epoch 920000: lr=0.00011, loss=0.4490
Epoch 920500: lr=0.00011, loss=0.4490
Epoch 921000: lr=0.00011, loss=0.4490
Epoch 921500: lr=0.00011, loss=0.4490
Epoch 922000: lr=0.00011, loss=0.4490
Epoch 922500: lr=0.00011, loss=0.4490
Epoch 923000: lr=0.00011, loss=0.4490
Epoch 923500: lr=0.00011, loss=0.4490
Epoch 924000: lr=0.00011, loss=0.4490
Epoch 924500: lr=0.00011, loss=0.4490
Epoch 925000: lr=0.00011, loss=0.4490
Epoch 925500: lr=0.00011, loss=0.4490
Epoch 926000: lr=0.00011, loss=0.4490
Epoch 926500: lr=0.00011, loss=0.4490
Epoch 927000: lr=0.00011, loss=0.4490
Epoch 927500: lr=0.00011, loss=0.4490
Epoch 928000: lr=0.00011, loss=0.4490
Epoch 928500: lr=0.00011, loss=0.4490
Epoch 929000: lr=0.00011, loss=0.4490
Epoch 929500: lr=0.00011, loss=0.4490
Epoch 930000: lr=0.00011, loss=0.4490
Epoch 930500: lr=0.00011, loss=0.4490
Epoch 931000: lr=0.00011, loss=0.4490
Epoch 931500: lr=0.00011, loss=0.4490
Epoch 932000: lr=0.00011, loss=0.4490
Epoch 932500: lr=0.00011, loss=0.4490
Epoch 933000: lr=0.00011, loss=0.4490
Epoch 933500: lr=0.00011, loss=0.4490
Epoch 934000: lr=0.00011, loss=0.4490
Epoch 934500: lr=0.00011, loss=0.4490
Epoch 935000: lr=0.00011, loss=0.4490
Epoch 935500: lr=0.00011, loss=0.4490
Epoch 936000: lr=0.00011, loss=0.4490
Epoch 936500: lr=0.00011, loss=0.4490
Epoch 937000: lr=0.00011, loss=0.4490
Epoch 937500: lr=0.00011, loss=0.4490
Epoch 938000: lr=0.00011, loss=0.4490
Epoch 938500: lr=0.00011, loss=0.4490
Epoch 939000: lr=0.00011, loss=0.4490
Epoch 939500: lr=0.00011, loss=0.4490
Epoch 940000: lr=0.00011, loss=0.4490
Epoch 940500: lr=0.00011, loss=0.4490
Epoch 941000: lr=0.00011, loss=0.4490
Epoch 941500: lr=0.00011, loss=0.4490
Epoch 942000: lr=0.00011, loss=0.4490
Epoch 942500: lr=0.00011, loss=0.4490
Epoch 943000: lr=0.00011, loss=0.4490
Epoch 943500: lr=0.00011, loss=0.4490
Epoch 944000: lr=0.00011, loss=0.4490
Epoch 944500: lr=0.00011, loss=0.4490
Epoch 945000: lr=0.00011, loss=0.4490
Epoch 945500: lr=0.00011, loss=0.4490
Epoch 946000: lr=0.00011, loss=0.4490
Epoch 946500: lr=0.00011, loss=0.4490
Epoch 947000: lr=0.00011, loss=0.4490
Epoch 947500: lr=0.00011, loss=0.4490
Epoch 948000: lr=0.00011, loss=0.4490
Epoch 948500: lr=0.00011, loss=0.4490
Epoch 949000: lr=0.00011, loss=0.4490
Epoch 949500: lr=0.00011, loss=0.4490
Epoch 950000: lr=0.00011, loss=0.4490
Epoch 950500: lr=0.00011, loss=0.4490
Epoch 951000: lr=0.00011, loss=0.4490
Epoch 951500: lr=0.00010, loss=0.4490
Epoch 952000: lr=0.00010, loss=0.4490
Epoch 952500: lr=0.00010, loss=0.4490
Epoch 953000: lr=0.00010, loss=0.4490
Epoch 953500: lr=0.00010, loss=0.4490
Epoch 954000: lr=0.00010, loss=0.4490
Epoch 954500: lr=0.00010, loss=0.4490
Epoch 955000: lr=0.00010, loss=0.4490
Epoch 955500: lr=0.00010, loss=0.4490
Epoch 956000: lr=0.00010, loss=0.4490
Epoch 956500: lr=0.00010, loss=0.4490
Epoch 957000: lr=0.00010, loss=0.4490
Epoch 957500: lr=0.00010, loss=0.4490
Epoch 958000: lr=0.00010, loss=0.4490
Epoch 958500: lr=0.00010, loss=0.4490
Epoch 959000: lr=0.00010, loss=0.4490
Epoch 959500: lr=0.00010, loss=0.4490
Epoch 960000: lr=0.00010, loss=0.4490
Epoch 960500: lr=0.00010, loss=0.4490
Epoch 961000: lr=0.00010, loss=0.4490
Epoch 961500: lr=0.00010, loss=0.4490
Epoch 962000: lr=0.00010, loss=0.4490
Epoch 962500: lr=0.00010, loss=0.4490
Epoch 963000: lr=0.00010, loss=0.4490
Epoch 963500: lr=0.00010, loss=0.4490
Epoch 964000: lr=0.00010, loss=0.4490
Epoch 964500: lr=0.00010, loss=0.4490
Epoch 965000: lr=0.00010, loss=0.4490
Epoch 965500: lr=0.00010, loss=0.4490
Epoch 966000: lr=0.00010, loss=0.4490
Epoch 966500: lr=0.00010, loss=0.4490
Epoch 967000: lr=0.00010, loss=0.4490
Epoch 967500: lr=0.00010, loss=0.4490
Epoch 968000: lr=0.00010, loss=0.4490
Epoch 968500: lr=0.00010, loss=0.4490
Epoch 969000: lr=0.00010, loss=0.4490
Epoch 969500: lr=0.00010, loss=0.4490
Epoch 970000: lr=0.00010, loss=0.4490
Epoch 970500: lr=0.00010, loss=0.4490
Epoch 971000: lr=0.00010, loss=0.4490
Epoch 971500: lr=0.00010, loss=0.4490
Epoch 972000: lr=0.00010, loss=0.4490
Epoch 972500: lr=0.00010, loss=0.4490
Epoch 973000: lr=0.00010, loss=0.4490
Epoch 973500: lr=0.00010, loss=0.4490
Epoch 974000: lr=0.00010, loss=0.4490
Epoch 974500: lr=0.00010, loss=0.4490
Epoch 975000: lr=0.00010, loss=0.4490
Epoch 975500: lr=0.00010, loss=0.4490
Epoch 976000: lr=0.00010, loss=0.4490
Epoch 976500: lr=0.00010, loss=0.4490
Epoch 977000: lr=0.00010, loss=0.4490
Epoch 977500: lr=0.00010, loss=0.4490
Epoch 978000: lr=0.00010, loss=0.4490
Epoch 978500: lr=0.00010, loss=0.4490
Epoch 979000: lr=0.00010, loss=0.4490
Epoch 979500: lr=0.00010, loss=0.4490
Epoch 980000: lr=0.00010, loss=0.4490
Epoch 980500: lr=0.00010, loss=0.4490
Epoch 981000: lr=0.00010, loss=0.4490
Epoch 981500: lr=0.00010, loss=0.4490
Epoch 982000: lr=0.00010, loss=0.4490
Epoch 982500: lr=0.00010, loss=0.4490
Epoch 983000: lr=0.00010, loss=0.4490
Epoch 983500: lr=0.00010, loss=0.4490
Epoch 984000: lr=0.00010, loss=0.4490
Epoch 984500: lr=0.00010, loss=0.4490
Epoch 985000: lr=0.00010, loss=0.4490
Epoch 985500: lr=0.00010, loss=0.4490
Epoch 986000: lr=0.00010, loss=0.4490
Epoch 986500: lr=0.00010, loss=0.4490
Epoch 987000: lr=0.00010, loss=0.4490
Epoch 987500: lr=0.00010, loss=0.4490
Epoch 988000: lr=0.00010, loss=0.4490
Epoch 988500: lr=0.00010, loss=0.4490
Epoch 989000: lr=0.00010, loss=0.4490
Epoch 989500: lr=0.00010, loss=0.4490
Epoch 990000: lr=0.00010, loss=0.4490
Epoch 990500: lr=0.00010, loss=0.4490
Epoch 991000: lr=0.00010, loss=0.4490
Epoch 991500: lr=0.00010, loss=0.4490
Epoch 992000: lr=0.00010, loss=0.4490
Epoch 992500: lr=0.00010, loss=0.4490
Epoch 993000: lr=0.00010, loss=0.4490
Epoch 993500: lr=0.00010, loss=0.4490
Epoch 994000: lr=0.00010, loss=0.4490
Epoch 994500: lr=0.00010, loss=0.4490
Epoch 995000: lr=0.00010, loss=0.4490
Epoch 995500: lr=0.00010, loss=0.4490
Epoch 996000: lr=0.00010, loss=0.4490
Epoch 996500: lr=0.00010, loss=0.4490
Epoch 997000: lr=0.00010, loss=0.4490
Epoch 997500: lr=0.00010, loss=0.4490
Epoch 998000: lr=0.00010, loss=0.4490
Epoch 998500: lr=0.00010, loss=0.4490
Epoch 999000: lr=0.00010, loss=0.4490
Epoch 999500: lr=0.00010, loss=0.4490

In [76]:
y_train_prob = predict_prob(X, w)

In [77]:
y_train_pred = (y_train_prob >= 0.5).astype(int)

In [78]:
accuracy = (y_train_pred == y).mean()
accuracy

np.float64(0.7901234567901234)

In [79]:
len(y_train_pred)

891

In [80]:
X_test = np.array(
    test[["Pclass", "Sex", "Age", "Embarked"]].values,
    dtype=float
)
X_test = np.c_[np.ones(X_test.shape[0]), X_test]

In [81]:
y_test_prob = predict_prob(X_test, w)
y_test_pred = (y_test_prob >= 0.5).astype(int)

In [82]:
len(y_test_pred)

418

In [83]:
y_test_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [84]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": y_test_pred
})

submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [85]:
submission.to_csv("submission.csv", index=False)

In [105]:
X_base = X

array([[ 1. ,  3. ,  0. , 34.5,  2. ],
       [ 1. ,  3. ,  1. , 47. ,  0. ],
       [ 1. ,  2. ,  0. , 62. ,  2. ],
       ...,
       [ 1. ,  3. ,  0. , 38.5,  0. ],
       [ 1. ,  3. ,  0. , 28. ,  0. ],
       [ 1. ,  3. ,  0. , 28. ,  1. ]], shape=(418, 5))

In [100]:
def add_bias(X):
    return np.c_[np.ones(X.shape[0]), X]

def accuracy_from_probs(y_prob, y_true, thresh=0.5):
    y_pred = (y_prob >= thresh).astype(int)
    return (y_pred == y_true).mean()

In [101]:
Pclass = X_base[:, 0]
Sex   = X_base[:, 1]
Age   = X_base[:, 2]
Emb   = X_base[:, 3]

X_poly = np.column_stack([
    X_base,
    Age**2,          # x^2 example
    Sex*Age,         # x1*x2 example
    Pclass*Age,
    Pclass*Sex,
    Age*Emb
])

In [102]:
X_poly_b = add_bias(X_poly)
w_poly, losses_poly = gradient_descent(X_poly_b, y, lr=0.01, epochs=5000)

Epoch 0: lr=0.01000, loss=0.6020
Epoch 500: lr=0.00667, loss=0.4835
Epoch 1000: lr=0.00500, loss=0.4773
Epoch 1500: lr=0.00400, loss=0.4733
Epoch 2000: lr=0.00333, loss=0.4705
Epoch 2500: lr=0.00286, loss=0.4684
Epoch 3000: lr=0.00250, loss=0.4667
Epoch 3500: lr=0.00222, loss=0.4653
Epoch 4000: lr=0.00200, loss=0.4642
Epoch 4500: lr=0.00182, loss=0.4632

In [103]:
y_prob_poly = predict_prob(X_poly_b, w_poly)
train_acc_poly = accuracy_from_probs(y_prob_poly, y)
train_acc_poly

np.float64(0.7901234567901234)

In [108]:
def build_poly_features(df):
    X_base = df[["Pclass", "Sex", "Age", "Embarked"]].to_numpy(dtype=float)

    Pclass = X_base[:, 0]
    Sex    = X_base[:, 1]
    Age    = X_base[:, 2]
    Emb    = X_base[:, 3]

    X_poly = np.column_stack([
        X_base,
        Age**2,
        Sex*Age,
        Pclass*Age,
        Pclass*Sex,
        Age*Emb
    ])
    return X_poly

In [109]:
X_train_poly = build_poly_features(train)
y_train = train["Survived"].to_numpy(dtype=float)

X_train_poly_b = add_bias(X_train_poly)

w_poly, losses_poly = gradient_descent(X_train_poly_b, y_train, lr=0.01, epochs=5000)
print("Train poly shape:", X_train_poly_b.shape, "w_poly shape:", w_poly.shape)

Epoch 0: lr=0.01000, loss=6.7732
Epoch 500: lr=0.00667, loss=5.0613
Epoch 1000: lr=0.00500, loss=6.8857
Epoch 1500: lr=0.00400, loss=4.8177
Epoch 2000: lr=0.00333, loss=3.7345
Epoch 2500: lr=0.00286, loss=3.8337
Epoch 3000: lr=0.00250, loss=3.3916
Epoch 3500: lr=0.00222, loss=3.4257
Epoch 4000: lr=0.00200, loss=3.4500
Epoch 4500: lr=0.00182, loss=3.7987
Train poly shape: (891, 10) w_poly shape: (10,)

/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3436777684.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))

In [110]:
X_test_poly = build_poly_features(test)
X_test_poly_b = add_bias(X_test_poly)

print("Test poly shape:", X_test_poly_b.shape, "w_poly shape:", w_poly.shape)

y_test_prob = predict_prob(X_test_poly_b, w_poly)
y_test_pred = (y_test_prob >= 0.5).astype(int)

Test poly shape: (418, 10) w_poly shape: (10,)

/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3436777684.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))

In [111]:
import pandas as pd

submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": y_test_pred
})

submission.to_csv("submission_poly.csv", index=False)

In [112]:
X_sa = train[["Sex", "Age"]].to_numpy(dtype=float)
X_sa_b = add_bias(X_sa)

w_sa, losses_sa = gradient_descent(X_sa_b, y, lr=0.01, epochs=5000)

y_prob_sa = predict_prob(X_sa_b, w_sa)
train_acc_sa = accuracy_from_probs(y_prob_sa, y)
train_acc_sa

Epoch 0: lr=0.01000, loss=0.7187
Epoch 500: lr=0.00667, loss=0.6159
Epoch 1000: lr=0.00500, loss=0.5930
Epoch 1500: lr=0.00400, loss=0.5796
Epoch 2000: lr=0.00333, loss=0.5707
Epoch 2500: lr=0.00286, loss=0.5644
Epoch 3000: lr=0.00250, loss=0.5596
Epoch 3500: lr=0.00222, loss=0.5559
Epoch 4000: lr=0.00200, loss=0.5528
Epoch 4500: lr=0.00182, loss=0.5503

np.float64(0.7665544332210998)

In [113]:
X_test_sa = test[["Sex", "Age"]].to_numpy(dtype=float)
X_test_sa_b = add_bias(X_test_sa)

y_test_prob_sa = predict_prob(X_test_sa_b, w_sa)
y_test_pred_sa = (y_test_prob_sa >= 0.5).astype(int)

submission = pd.DataFrame({"PassengerId": test["PassengerId"], "Survived": y_test_pred_sa})
submission.to_csv("submission_sex_age.csv", index=False)

In [114]:
X_lin = train[["Pclass", "Sex", "Age", "Embarked"]].to_numpy(dtype=float)
X_lin_b = add_bias(X_lin)
y = train["Survived"].to_numpy(dtype=float)

In [115]:
def linear_predict(X, w):
    return X @ w

def linear_mse(X, y, w):
    e = linear_predict(X, w) - y
    return np.mean(e**2)

def linear_gd(X, y, lr=0.01, epochs=5000):
    w = np.zeros(X.shape[1])
    for i in range(epochs):
        grad = (2/len(y)) * (X.T @ (X @ w - y))  # gradient of MSE
        w -= lr * grad
        if i % 500 == 0:
            print(f"Epoch {i}: MSE={linear_mse(X,y,w):.4f}")
    return w

In [116]:
w_lin_gd = linear_gd(X_lin_b, y, lr=0.01, epochs=5000)

Epoch 0: MSE=44.8420
Epoch 500: MSE=nan
Epoch 1000: MSE=nan
Epoch 1500: MSE=nan
Epoch 2000: MSE=nan
Epoch 2500: MSE=nan
Epoch 3000: MSE=nan
Epoch 3500: MSE=nan
Epoch 4000: MSE=nan
Epoch 4500: MSE=nan

/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3515087814.py:11: RuntimeWarning: overflow encountered in matmul
  grad = (2/len(y)) * (X.T @ (X @ w - y))  # gradient of MSE
/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3515087814.py:11: RuntimeWarning: invalid value encountered in matmul
  grad = (2/len(y)) * (X.T @ (X @ w - y))  # gradient of MSE
/var/folders/0p/v7vlt28j0f59fgqf920_rlxh0000gn/T/ipykernel_9088/3515087814.py:12: RuntimeWarning: invalid value encountered in subtract
  w -= lr * grad

In [117]:
y_hat = linear_predict(X_lin_b, w_lin_gd)
y_pred = (y_hat >= 0.5).astype(int)
train_acc_lin = (y_pred == y).mean()
train_acc_lin

np.float64(0.6161616161616161)

In [118]:
X_test_lin = test[["Pclass", "Sex", "Age", "Embarked"]].to_numpy(dtype=float)
X_test_lin_b = add_bias(X_test_lin)

y_hat_test = linear_predict(X_test_lin_b, w_lin_gd)
y_test_pred = (y_hat_test >= 0.5).astype(int)

submission = pd.DataFrame({"PassengerId": test["PassengerId"], "Survived": y_test_pred})
submission.to_csv("submission_linear_gd.csv", index=False)

In [119]:
w_lin_inv = np.linalg.inv(X_lin_b.T @ X_lin_b) @ (X_lin_b.T @ y)

In [120]:
mse_weights = np.mean((w_lin_inv - w_lin_gd)**2)
mse_weights

np.float64(nan)